---
title: "Describing Places"
sidebar: true
toc: true
page-layout: full
format: html
editor: visual
---

## Session Description

In this session, we'll spend time talking about how to describe places, as well as some frameworks for making place comparisons. We will think about how the types of stories we tell about places connect with typical arguments and tropes which guide place description and analysis within urban planning and policy settings.

In addition to our discussion of places, we'll debrief your two labs from last week and introduce this week's lab.

## Before Class

D'Ignazio, Catherine, and Lauren F. Klein. (2020). *Data Feminism*. MIT Press. Chapter 5 [{{< fa file >}}](https://uofi.box.com/s/8pfpb8mgzfmqve2goo4oehm0s0gdgsra), Chapter 6 [{{< fa file >}}](https://uofi.box.com/s/emfzi13q82lpipsgbc0antmrxm4994f8), Chapter 7 [{{< fa file >}}](https://uofi.box.com/s/713yeczrs3ekh2k86je46vixep8d9d0e)

Lynch, Kevin. (1960). *The Image of the City*. Chapter 3 [{{< fa file >}}](https://uofi.box.com/s/khfdu0cbm2aj1xb5ktkdrplih1jrwnb2).

## Reflect

-   We intuitively tell lots of stories about places. What are some of the most evocative tropes you can think of that could apply to places? What makes for a good story about place?
-   What are some of the benefits and challenges of making place comparisons? How does this feel from the perspective of an analyst? What dangers or challenges does the analyst face when telling comparative stories to others?
-   Your readings from *Data Feminism* discuss embracing pluralism in data storytelling. What might this look like in the context of describing systems of neighborhoods?

## Slides

```{=html}
<iframe class="slide-deck" src="../slides/S6 Describing Places/index.html" style="width:100%;height:50vh;margin:0;padding:0"; frameborder="2"></iframe>
```

## Resources for Further Exploration

Anti-Eviction Mapping Project [{{< fa link >}}](https://antievictionmap.com)

Eviction Lab Methodology [{{< fa link >}}](https://evictionlab.org/eviction-tracking/methods/)

Bloomberg: What's Really Warming the World [{{< fa link >}}](https://www.bloomberg.com/graphics/2015-whats-warming-the-world/)

Design Justice Project [{{< fa link >}}](https://www.media.mit.edu/projects/design-justice-auditing/overview/)

Global Atlas of Environmental Justice [{{< fa link >}}](https://ejatlas.org)

Five Thirty Eight: Kidnapping of Girls in Nigeria Is Part of a Worsening Problem [{{< fa link >}}](https://fivethirtyeight.com/features/nigeria-kidnapping/)

Memorandum on Transparency and Open Government [{{< fa link >}}](https://www.archives.gov/files/cui/documents/2009-WH-memo-on-transparency-and-open-government.pdf)
