---
title: "Final Project Check-In: Wednesday"
sidebar: true
toc: true
page-layout: full
format: html
editor: visual
---

## Session Description

We'll continue to check-in and workshop your final projects. For this session, we'll be examining your *best evidence* - the facts or analysis that you believe best makes the point you're trying to convey to your audience.

Come to class prepared to share your best evidence with the entire class. You will each be asked to take a few minutes to present your best evidence and recieve feedback on it.

## Before Class

Prepare your best evidence for sharing. This might be preparing or exporting a bit of analysis or coming the class prepared to articulate and share this evidence.

To help expedite our workshopping of best evidence, please reply to this email with a single slide containing your best evidence (PowerPoint, Keynote, or PDF are fine). I will compile these in advance of the class so that we can spend as much time as possible workshopping each of your arguments and evidence. To maximize our ability to share and workshop, we’ll split into two groups – Ouafa will work with one group, and I will work with the other.
 
Please email me your best evidence slide before 9am tomorrow (Wednesday) morning. This slide does not need to be visually refined – it just needs your name and the evidence in whatever form you plan to share it (image, map, table, whatever).

## Reflect

1.  How does this evidence support the point you're trying to make?

2.  How do you plan to use the evidence in your argument?

3.  What critiques might others have regarding your evidence? How are you planning to preemptively engage these critiques in your analysis?

## Slides

No slides for this session.

## Resources for Further Exploration
