---
title: "Health Equity"
sidebar: true
toc: true
page-layout: full
format: html
editor: visual
---

## Session Description

We will be joined for our class session today by [Dr. Christine Joseph](https://www.henryford.com/physician-directory/j/joseph-christine), of Henry Ford Health. Dr. Joseph does work that examines the social determinants of health and health disparities. She will share some of her perspective on why neighborhoods matter and form an important framework for analysis within her work.

## Before Class

## Reflect

1.  What are some tropes or conventions we use to talk about individual health? Collective health?

2.  How might health disparities (at a neighborhood or population level) be connected to the many themes we've talked about in this class?

3.  Is population health a planning issue? What role do practitioners and researchers in planning have for influencing how we think and act around health at the neighborhood level?

## Slides

## Resources for Further Exploration
