---
title: "Field Observations"
sidebar: true
toc: true
page-layout: full
format: html
editor: visual
---

## Session Description

So far, we have started to learn how to tell stories about places using existing indicators. With so many available sources of existing information, it can be easy to experience a disconnect between the values of those indicators and the complexity of what they represent. To think more about what grounds our analysis as planners, we will go explore a neighborhood in person and then think through elements of the stories that may help us describe that place through indicators.

We are going to spend this class session doing field observation of the West Urbana neighborhood which we read about during the first week of class. This neighborhood is designated as an American Planning Association Great Place in America. We will meet at Carle Park in Urbana at the intersection of Carle and Indiana streets. We will not meet in CIF for this session.

Come prepared to spend the course session exploring the neighborhood. We will use the insights you gather during this course session to inform Thursday's lab assignment.

## Before Class

-   Write a short reflection on your pre-existing impressions of the West Urbana neighborhood. Some of you may be very familiar, and others may not at all. Reflect based upon what you know or have heard.
-   Wear comfortable clothes, and be prepared to be outside for the duration of our course session.
-   You may wish to bring a notebook with you as well as a phone or camera to document your observations.

## During Class

We will split up into small groups in order to observe elements of the West Urbana Neighborhood (group assignments are below). Working in groups of four or five, you will each be responsible for focusing on one element of observation (you may double up in an area of your choice if you have five in your group):

1.  Infrastructure and Environment
2.  Economy and Housing
3.  Health and Wellbeing
4.  Sense of Place

**Observation 1:** In your group, spend 20 minutes walking around the neighborhood, taking in and observing your specific element. Then take 5-10 minutes to write down your overall impressions and any questions you have after this brief exploration.

**Observation 2:** As a group, pick a block to systematically analyze. Spend 20 minutes observing your specific element as it is reflected on your block. You may want to take pictures, sketch a map, or use other methods to record what you observe.

**Observation 3:** Spend the remaining 30 minutes comparing notes with your other group members. Record a list of shared questions you have about the block and portions of the neighborhood that you explored. Reflect as a group upon what you were able to observe.

At the end of our class time you can leave. Please bring your individual and shared reflections and observational materials to Thursday's lab session.

## Reflect

## Slides

## Resources for Further Exploration

[Urban Institute: Observation](https://www.urban.org/research/data-methods/data-collection/observation)

[Participant Observation and the Development of Urban Neighborhood Policy](https://files.eric.ed.gov/fulltext/ED068597.pdf)
