---
title: "Field Observations"
sidebar: true
toc: true
page-layout: full
format: html
editor: visual
---

## Session Description

On Monday, we spent time working together to develop a strategy for the systematic examination of the West Urbana neighborhood. We are going to spend this class session doing field observation of the West Urbana neighborhood which is designated as an American Planning Association Great Place. We will meet at Carle Park in Urbana at the intersection of [Carle and Indiana streets](https://goo.gl/maps/pgxMw527zC1zdsv8A).

Come prepared to spend the course session exploring the neighborhood.

## Session Goals

1.  Collaboratively build a story about the West Urbana neighborhood that leverages both your knowledge of existing indicators.
2.  Reflect upon the tactical and design choices you have made in telling your story.

## Before Class

-   Review your notes and materials from your pre-visit work on Monday.
-   Wear comfortable clothes, and be prepared to be outside for the duration of our course session.
-   You may wish to bring a notebook with you as well as a phone or camera to document your observations.

## During Class

We will split up into  groups in order to observe elements of the West Urbana Neighborhood (as a reminder, Monday's group assignments are below). Working in groups, each group member will be responsible for focusing on one element of observation (you may double up in an area of your choice if you have more than four in your group):

1.  Infrastructure and Environment
2.  Economy and Housing
3.  Health and Wellbeing
4.  Sense of Place

**Observation 1:** In your group, spend 20 minutes walking around the neighborhood, taking in and observing your specific element. Then take 5-10 minutes to write down your overall impressions and any questions you have after this brief exploration.

**Observation 2:** As a group, pick a block to systematically analyze. Spend 20 minutes observing your specific element as it is reflected on your block. You may want to take pictures, sketch a map, or use other methods to record what you observe.

**Observation 3:** Spend the remaining 30 minutes comparing notes with your other group members. Record a list of shared questions you have about the block and portions of the neighborhood that you explored. Reflect as a group upon what you were able to observe.

At the end of our class time you can leave. 

## Groups

### Group 1
Rafi A., Natalia F., Tak L., Elizabeth R., Tingxuan T.

### Group 2
Priyanka C., Prithvi H., Bo P., Aditya S.

### Group 3
Julia P., Chestha K., Rose R., Shiva S.

### Group 4
Linda D., Aakanksha K., Josh R., Luke T.

## After Class

Draw upon your shared memo and your individual observations to develop a short reflection on the process. 

1. Share your initial reflection on what you knew about the neighborhood before you visited.

2. Share a brief summary of your group's thoughts and information priorities coming from Monday's pre-field work preparation.

3. Share your field observations, focusing on the element which you were responsible for describing.

4. Share your reflections on what you know now and what you experienced in attempting to systematically observe the neighborhood and communicate its qualities.

5. Think carefully about what your next steps might (hypothetically be) following your initial field observation. 

Push your individual reflections to your lab GitHub repository. 

## Slides

## Resources for Further Exploration
