---
title: "Final Project Peer Review"
sidebar: true
toc: true
page-layout: full
format: html
editor: visual
---

## Session Description

As we approach the end of the semester, the remainder of our time together will focus on strengthening your final projects. By this point, you should have most of the constituent pieces for this final project as reflected within the memos you've produced over the course of the semester. Your task is to now translate these pieces into a coherent and polished final report.

One valuable form of support we've used over the course of the semester is peer review. Today's session and our next session will focus on working in small groups to introduce your final projects, set work goals for this week, and then use peer review as a way to further develop and improve some of those components of your final report.

In this session, we'll set the context for peer review of each others' work. You will split into small groups and spend time introducing your final projects to each other. At the end of this course session, you will share with your peer review team an analytic component which you'd like their feedback on. During our Thursday session, they will provide direct written feedback, and you will have time to incorporate some of this feedback into your work and make adjustments and refinements during class time.

## Before Class

-   Think about the main message you wish to convey in your policy report - can you encapsulate that message in a declarative sentence or two?
-   Think about one critical component of your final project - this could be a key figure, key analytic concept, key measure, or key outcome. Come prepared to share what this is with your peer review partners.
-   Think about key visual or analytic elements you can share with your peer reviewers to offer them context on your project. Come prepared to share this in class.

## During Class

You should develop written feedback to share on your peer review team members' work, and should be prepared to receive feedback on your own work. Please also come prepared to start incorporating that feedback into your work products.

Your feedback for each of your teammates should build upon the following prompts:

-   Based upon what you heard in your sharing time, what's the main message or point of their final project?
-   Who do you see as the target audience for their report?
-   What insights will this work provide?

Thinking about the work component they shared with you...

-   What works well about this component?
-   What do you think could be improved about this component?
-   What questions do you have after reviewing this component?

## Reflect

## Slides

## Resources for Further Exploration
