---
title: "Final Presentations"
sidebar: true
toc: true
page-layout: full
format: html
editor: visual
---

## Session Description

You made it! This is the final session for Neighborhood Analysis. Most of our time will focus on presentations, but I will also recap what we have covered over the course of the semester, as well as some next steps in your journey as neighborhood analysts.

## Today's Presenters

Reminder - each presenter has eight minutes to share.

1.  Bo P.
2.  Shiva S.
3.  Elizabeth R.
4.  Prithvi H.
5.  Linda D.
6.  Natalia F.
7.  Priyanka C.
8.  Aditya S.
9.  Tak L.

## Providing Feedback

Please provide feedback to each other in the [following form](https://forms.gle/KUcP3Ek23b4uymQh6) - I will consolidate your written feedback on each presentation and will send it to you.

## Reflect

Some questions to seed end of class reflections:

1.  Are there things that you wish we covered over the course of the semester that we didn't?

2.  Are there ways that Professor Greenlee could have better supported learning (individually and collectively) over the course of the semester?

3.  Was there sufficient balance between technical and non-technical content?

4.  Were labs and other supporting materials clear? Were there resources or content you wish you had to support your independent learning using this format?

## Slides

## Resources for Further Exploration
