---
title: "Place Background Memorandum"
sidebar: true
toc: true
page-layout: full
format: html
editor: visual
---

## Introduction

In your previous memorandum, you identified a place to focus your analysis on, and provided some preliminary justification for your choice. In this memorandum, you will leverage additional research to identify priority populations, issues, and neighborhoods, and also to lay out an analysis roadmap that will guide your subsequent analysis.

## Goals

-   Add more thought and detail to your previous place selection memorandum

-   Draw upon a range of sources to critically analyze the place you selected

-   Use research to develop priorities for exploratory analysis

## Your Place Background Memorandum

Drawing from external sources and your own research, prepare a memorandum of around 2,000 words that provides background on your chosen place. Your memorandum should provide some general background on your place, and should then identify one or several key issues that will guide your subsequent analysis and work over the course of the semester. Key issues should be guided by a combination of your interests and what you can justify as relevant given your background research.

Below, please find some guiding questions to help you structure your memorandum:

-   What is the overall history of your place? What are the types of issues that have mattered in the past, and what types of issues matter at present?

-   Which neighborhoods or subareas of your place are frequently mentioned in local plans, reports, or journalistic accounts? What differentiates those neighborhoods? At what geographic scale can these subareas be classified or analyzed?

-   Based upon your background research, are there any population groups that are likely to warrant special attention. Why?

-   Based upon your background research, are there policy issues or debates that warrant special attention or that could benefit from detailed analysis. What are these, and what factors are important for understanding them?

-   Based upon your exploration, identify key themes and indicators which you believe will be important to focus on in your subsequent analyses. What types of strategies do you intend to use in order to examine these themes and indicators?

## Submission Instructions

Follow [this link](https://classroom.github.com/a/bNEK_LWx) to accept the lab Github Classroom assignment repository. Save your memorandum as a Quarto markdown document and upload along with your post-assignment reflection to GitHub.

### Assignment Reflection

In the repository you downloaded for your assignment, you will find a separate reflection document. Please respond to the following prompts in that document and submit along with your assignment repository.

1.  Highlight one or two things you are especially proud of regarding your submission. This could be a particular element within the assignment or could be part of your process (e.g. time management, applying new techniques, etc.).

2.  If you were to start this assignment over again, what are one or two things that you might do differently?

3.  Are there any aspects or areas in your submission where you would like us to focus our feedback?

4.  On a scale of 1 to 10, please rate how ready you feel this work is for sharing with a public audience (where 1 is not at all ready to be shared and 10 is polished and ready for public dissemination).
