{
  "hash": "cef1b63ab3eb56a842cfd0f570c0af32",
  "result": {
    "markdown": "---\ntitle: \"Neighborhood Change\"\nsidebar: false\ntoc: true\ntoc-depth: 4\npage-layout: full\nbibliography: ../references.bib\ncsl: ../apa-6th-edition.csl\nformat: \n  html:\n    code-fold: show\n    code-overflow: wrap\n    code-tools:\n      source: true\n      toggle: false\n      caption: none\nfig-responsive: true\neditor: visual\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gt)\nlibrary(tidycensus)\nlibrary(tidyverse)\n```\n:::\n\n\n## Introduction\n\nIn this lab, we'll explore in detail the [Nathalie P. Voorhees Center's](https://voorheescenter.uic.edu) methodology for measuring neighborhood change. The center has produced multiple analyses and strategies for measuring such change, focused on the Chicago metropolitan area.\n\nBy the end of this lab, you will replicate elements of the Voorhees Center's *Who Can Live in Chicago?* report including maps and other visualizations of neighborhood change. We will develop a code base that could be applied to any location in the United States.\n\n## Goals\n\nIn this lab, we will use a combination of decennial census data and American Community Survey data to examine patterns of neighborhood income change. We will overlay on these patterns of income change information about the demographics of who lives in these neighborhoods. Our goals for this lab are as follows:\n\n-   Continue to work with common sources of sociodemographic information, including those that have been pre-processed by sources other than the Census Bureau.\n-   Think critically about data processing pipelines and data requirements.\n-   Explore strategies for spatial longitudinal data description and analysis.\n\nTaking a close look at the visuals from the [Voorhees Center website](https://voorheescenter.uic.edu/chicago_communities/), they calculate for each census tract in each year the average per capita income for the time periods 1970, 1980, 1990, 2000, 2010, and 2017 for each census tract and then compare it to the regional weighted average income.\n\n![](08_neighborhood_change/images/02_NVC_Combined-Decades.png)\n\nThey classify tracts based upon whether they are:\n\n-   **Very High Income:** Greater than 40% above the regional average\n-   **High Income:** 20% - 40% above the reg ional average\n-   **Middle Income:** 20% below to 20% above the regional average\n-   **Low Income:** 20% below to 40% below the regional average\n-   **Very Low Income:** Greater than 40% below the regional average\n\nAfter classifying tracts, the study examines change over time, and then examines recent demographic characteristics based upon this change.\n\n![](08_neighborhood_change/images/03_NVC_Three_Cities.png) This gives us a sense of what we need to do to prepare our data.\n\n## Github Lab Repository\n\nIf you have not already done so, follow [this link](https://classroom.github.com/a/QZUuklCL) to accept the lab Github Classroom assignment repository.\n\n## Introduction to LTDB Data\n\nAt this point, you have spent time working with census data and common census geographies. We have used the tidycensus package to download census data from the Census Bureau's servers using API calls.\n\nIn this lab, we are going to look at another source of historical census data - the Longitudinal Tract Database. Census tracts are a common geography used by planners and other analysts because tracts roughly approximate neighborhoods, especially in highly urbanized areas where population density means that tracts are relatively small. One challenge faced by analysts looking to examine neighborhood level characteristics over time is that the geographic definitions for census tracts change every 10 years following the decennial census. These changes are performed as part of the Census' [Participant Statistical Areas Program (PSAP)](https://www.census.gov/programs-surveys/decennial-census/about/psap.html).\n\nWhile some tracts may stay the same, some may be *split* in cases where the population increases, and others may be *merged* in cases where the population decreases. See this [quick reference guide](https://www2.census.gov/geo/pdfs/partnerships/psap/G-650.pdf) for more information on thresholds for redefinition:\n\n![](08_neighborhood_change/images/04_2020PSAP.png)\n\nThe Census Bureau produces [geographic relationship files](https://www.census.gov/geographies/reference-files/time-series/geo/relationship-files.2020.html) which can help show the relationships between geographies over time.\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"dmoicsmsyk\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#dmoicsmsyk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dmoicsmsyk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dmoicsmsyk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dmoicsmsyk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dmoicsmsyk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dmoicsmsyk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dmoicsmsyk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dmoicsmsyk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dmoicsmsyk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dmoicsmsyk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dmoicsmsyk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dmoicsmsyk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dmoicsmsyk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dmoicsmsyk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dmoicsmsyk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dmoicsmsyk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dmoicsmsyk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmoicsmsyk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dmoicsmsyk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dmoicsmsyk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmoicsmsyk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dmoicsmsyk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dmoicsmsyk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dmoicsmsyk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmoicsmsyk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dmoicsmsyk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dmoicsmsyk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dmoicsmsyk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dmoicsmsyk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmoicsmsyk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dmoicsmsyk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmoicsmsyk .gt_left {\n  text-align: left;\n}\n\n#dmoicsmsyk .gt_center {\n  text-align: center;\n}\n\n#dmoicsmsyk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dmoicsmsyk .gt_font_normal {\n  font-weight: normal;\n}\n\n#dmoicsmsyk .gt_font_bold {\n  font-weight: bold;\n}\n\n#dmoicsmsyk .gt_font_italic {\n  font-style: italic;\n}\n\n#dmoicsmsyk .gt_super {\n  font-size: 65%;\n}\n\n#dmoicsmsyk .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#dmoicsmsyk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dmoicsmsyk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dmoicsmsyk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dmoicsmsyk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dmoicsmsyk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dmoicsmsyk .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">GEOID_TRACT_10</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">GEOID_TRACT_20</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">NAMELSAD_TRACT_10</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">NAMELSAD_TRACT_20</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">AREALAND_TRACT_10</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">AREALAND_TRACT_20</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">01001020100</td>\n<td class=\"gt_row gt_right\">01001020100</td>\n<td class=\"gt_row gt_left\">Census Tract 201</td>\n<td class=\"gt_row gt_left\">Census Tract 201</td>\n<td class=\"gt_row gt_right\">9,827,271</td>\n<td class=\"gt_row gt_right\">9,825,304</td></tr>\n    <tr><td class=\"gt_row gt_right\">01001020200</td>\n<td class=\"gt_row gt_right\">01001020100</td>\n<td class=\"gt_row gt_left\">Census Tract 202</td>\n<td class=\"gt_row gt_left\">Census Tract 201</td>\n<td class=\"gt_row gt_right\">3,325,674</td>\n<td class=\"gt_row gt_right\">9,825,304</td></tr>\n    <tr><td class=\"gt_row gt_right\">01001020200</td>\n<td class=\"gt_row gt_right\">01001020200</td>\n<td class=\"gt_row gt_left\">Census Tract 202</td>\n<td class=\"gt_row gt_left\">Census Tract 202</td>\n<td class=\"gt_row gt_right\">3,325,674</td>\n<td class=\"gt_row gt_right\">3,320,818</td></tr>\n    <tr><td class=\"gt_row gt_right\">01001020300</td>\n<td class=\"gt_row gt_right\">01001020300</td>\n<td class=\"gt_row gt_left\">Census Tract 203</td>\n<td class=\"gt_row gt_left\">Census Tract 203</td>\n<td class=\"gt_row gt_right\">5,349,271</td>\n<td class=\"gt_row gt_right\">5,349,271</td></tr>\n    <tr><td class=\"gt_row gt_right\">01001020400</td>\n<td class=\"gt_row gt_right\">01001020400</td>\n<td class=\"gt_row gt_left\">Census Tract 204</td>\n<td class=\"gt_row gt_left\">Census Tract 204</td>\n<td class=\"gt_row gt_right\">6,384,282</td>\n<td class=\"gt_row gt_right\">6,384,282</td></tr>\n    <tr><td class=\"gt_row gt_right\">01001020500</td>\n<td class=\"gt_row gt_right\">01001020501</td>\n<td class=\"gt_row gt_left\">Census Tract 205</td>\n<td class=\"gt_row gt_left\">Census Tract 205.01</td>\n<td class=\"gt_row gt_right\">11,408,867</td>\n<td class=\"gt_row gt_right\">6,203,654</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nNote from these example records shifts in tract definitions and areas. These relationship files can help you identify which census tracts have changed, however, creating consistent estimates over time from this information is challenging. Researchers tend to use strategies that either attribute characteristics using either *area* or *share of population* to weight how portions of one tract might translate into a new boundary in a different year.\n\nBrown University's [Spatial Structures in the Social Sciences](https://s4.ad.brown.edu/projects/diversity/index.htm) group has produced a [Longitudinal Tract Database](https://s4.ad.brown.edu/projects/diversity/researcher/LTDB.htm) which provides demographic estimates for prior decennial census years 1970, 1980, 1990, and 2000 adjusted to 2010 boundaries. The files also include selected demographic indicators that are comparable across each of these decennial census enumerations (the questions are asked in the same or similar enough way to be able to reliably compare these qualities over time).\n\nLTDB data come from two sources:\n\n1.  Decennial \"short form\" census data from the 100 percent count of the population. This includes race and ethnicity, age, household composition, and household tenure information.\n\n2.  Decennial \"long form\" census data administered to a sample of 1 in 6 households. These surveys contain far more detailed information on the characteristics of the population.\n\nDecennial data continues to be collected, but the 1 in 6 count sample data has now been replaced by the American Community Survey which annually samples the population creating valuable intercensal estimates used by analysts today.\n\nYou can find more information about the LTDB in the following [technical documentation](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4134912/pdf/nihms-522336.pdf).\n\nIn order to examine income and demographic change for census tracts, we're going to use LTDB data, and ultimately will supplement what's in these data with additional ACS data. We do this so that we can compare estimates over time using the same census tract geographies.\n\n## Setup\n\nLet's get set up by loading a few packages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gt)\nlibrary(tidyverse)\n```\n:::\n\n\n### LTDB Data Download\n\nLet's start by downloading LTDB data for analysis.\n\nGo to the [data download](https://s4.ad.brown.edu/projects/diversity/researcher/LTBDDload/Default.aspx) page. You will need to enter your email address and certify that you will follow terms of use for the data.\n\nMake note of what datasets are aggregated in the LTDB Standard Datasets. ![](08_neighborhood_change/images/01_ltdb.png)\n\nDownload both the *full* and *sample* standard data set files for all years. Also download the codebook.\n\nDecompress the downloaded folder containing the data files and place the raw data csv files in your raw data folder. You should have 12 files - six \"fullcount\" files and six \"sample\" files (you can ignore those files in the fullcount download with \"Global Neighborhood\" in their file name).\n\nPlace the codebook in your data documentation folder.\n\nNow that we have data and documentation manually downloaded, we can import the data for analysis.\n\n### Data Import\n\n\n::: {.cell}\n\n:::\n\n\nLet's import our data. These are csv files - in the past we've used `read_csv()` from the readr package to do this (readr is part of the tidyverse so you don't need to load it separately).\n\nFor clarity, use the prefix \"F\\_\" for full count data and \"S\\_\" for sample data when you read the LTDB into table objects in R. Go ahead and import the ten data files:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_1970<-read_csv(\"data_raw/LTDB_Std_1970_fullcount.csv\")\nS_1970<-read_csv(\"data_raw/ltdb_std_1970_sample.csv\")\n\nF_1980<-read_csv(\"data_raw/LTDB_Std_1980_fullcount.csv\")\nS_1980<-read_csv(\"data_raw/ltdb_std_1980_sample.csv\")\n\nF_1990<-read_csv(\"data_raw/LTDB_Std_1990_fullcount.csv\")\nS_1990<-read_csv(\"data_raw/ltdb_std_1990_sample.csv\")\n\nF_2000<-read_csv(\"data_raw/LTDB_Std_2000_fullcount.csv\")\nS_2000<-read_csv(\"data_raw/ltdb_std_2000_sample.csv\")\n\nF_2010<-read_csv(\"data_raw/LTDB_Std_2010_fullcount.csv\")\nS_2010<-read_csv(\"data_raw/LTDB_std_200812_Sample.csv\")\n\nF_2020<-read_csv(\"data_raw/LTDB_Std_2020_fullcount.csv\")\nS_2020<-read_csv(\"data_raw/LTDB_std_201519_Sample.csv\")\n```\n:::\n\n\nNow that we have all of the data loaded, we can start working on preparing it for analysis.\n\n## Data Preparation\n\n### Isolate Income Data\n\nWe need to start by identifying the variable(s) containing income information. Go into the data codebook and search for income. We have information on median household income, some breakdowns by race and ethnicity, and per-capita income.\n\nLet's move forward with the per-capita income information, since this is what is listed in the Voorhees study. We will need to pull that information from each of the data years 1970, 1980, 1990, 2000, 2010 (as proxied by 2008-2012 ACS data, and 2020 (as proxied by 2014 - 2019 ACS data)).\n\nFor each of the five decades, create a new dataset inc\\_\\[year\\] that contains the 2010 tract identifier (TRTID10), and the income per capita variable (INCPC\\[year\\]). For the 2010 data, also include the state identified (statea), the county identified (countya), and the tract identifier (tracta):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninc_70<-S_1970 |> select(TRTID10, INCPC70)\ninc_80<-S_1980 |> select(trtid10, incpc80)\ninc_90<-S_1990 |> select(TRTID10, INCPC90)\ninc_00<-S_2000 |> select(TRTID10, INCPC00)\ninc_10<-S_2010 |> select(tractid, incpc12)\ninc_20<-S_2020 |> select(tractid, statea, countya, tracta, incpc19)\n```\n:::\n\n\nNow that we've isolated the income per capita data, we can start to think about how we'd join it all together for the purposes of mapping and further analysis.\n\nOne thing we should immediately note here is that there are different numbers of observations for each year. For instance, inc_20 (observations for 2020) contains 73,056 observations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(inc_20)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 73056\n```\n:::\n:::\n\n\ninc_70 contains 52,759 observations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(inc_70)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 52759\n```\n:::\n:::\n\n\nThis should guide our strategy for how we join the data together. Our join strategy should try to keep all records corresponding to the observation years that have more observations (this is due to differences in geographic coverage between each decade).\n\nAnother thing we may want to handle before we join the data together are to standardize column names. You'll note from selecting columns and constructing the inc\\_\\[year\\] datasets that there's different capitalization and naming for some years. We can fix this when we're selecting our data by specifying \\[new name\\] = \\[column name\\] in our select calls:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninc_70<-S_1970 |> select(TRTID10, INCPC70)\ninc_80<-S_1980 |> select(TRTID10 = trtid10, incpc80)\ninc_90<-S_1990 |> select(TRTID10, INCPC90)\ninc_00<-S_2000 |> select(TRTID10, INCPC00)\ninc_10<-S_2010 |> select(TRTID10 = tractid, INCPC12 = incpc12)\ninc_20<-S_2020 |> select(TRTID10 = tractid, STATE = statea, COUNTY = countya, TRACT = tracta, INCPC19 = incpc19)\n```\n:::\n\n\nWe have another major problem to deal with before we can join these data together. Take a look at the column types using the `str()` command:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(inc_70)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntibble [52,759 × 2] (S3: tbl_df/tbl/data.frame)\n $ TRTID10: num [1:52759] 1e+09 1e+09 1e+09 1e+09 1e+09 ...\n $ INCPC70: num [1:52759] 2850 2597 2876 2567 2847 ...\n```\n:::\n\n```{.r .cell-code}\nstr(inc_80)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntibble [59,187 × 2] (S3: tbl_df/tbl/data.frame)\n $ TRTID10: num [1:59187] 1e+09 1e+09 1e+09 1e+09 1e+09 ...\n $ incpc80: num [1:59187] 0 4648 5804 7668 6339 ...\n```\n:::\n\n```{.r .cell-code}\nstr(inc_90)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntibble [72,693 × 2] (S3: tbl_df/tbl/data.frame)\n $ TRTID10: num [1:72693] 1e+09 1e+09 1e+09 1e+09 1e+09 ...\n $ INCPC90: num [1:72693] 11663 8555 11782 15323 14492 ...\n```\n:::\n\n```{.r .cell-code}\nstr(inc_00)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntibble [72,693 × 2] (S3: tbl_df/tbl/data.frame)\n $ TRTID10: num [1:72693] 1e+09 1e+09 1e+09 1e+09 1e+09 ...\n $ INCPC00: num [1:72693] 17771 14217 18346 19741 24492 ...\n```\n:::\n\n```{.r .cell-code}\nstr(inc_10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntibble [73,056 × 2] (S3: tbl_df/tbl/data.frame)\n $ TRTID10: chr [1:73056] \"01101005302\" \"01101005402\" \"01101001800\" \"01095030600\" ...\n $ INCPC12: num [1:73056] 18084 18006 24799 21889 16953 ...\n```\n:::\n\n```{.r .cell-code}\nstr(inc_20)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntibble [73,056 × 5] (S3: tbl_df/tbl/data.frame)\n $ TRTID10: chr [1:73056] \"01073001100\" \"01073001400\" \"01073002000\" \"01073003802\" ...\n $ STATE  : chr [1:73056] \"Alabama\" \"Alabama\" \"Alabama\" \"Alabama\" ...\n $ COUNTY : chr [1:73056] \"Jefferson County\" \"Jefferson County\" \"Jefferson County\" \"Jefferson County\" ...\n $ TRACT  : chr [1:73056] \"Census Tract 11\" \"Census Tract 14\" \"Census Tract 20\" \"Census Tract 38.02\" ...\n $ INCPC19: num [1:73056] 21518 20209 15153 17416 16570 ...\n```\n:::\n:::\n\n\nSome of our TRTID10 colums are defined as character and others as numeric. Although these FIPS codes look like numbers, they are unique IDs and we want to make sure that they are consistently stored as character vectors. This is also important, because some of the states that come early in the alphabet start with \"0\" (for instance, Alabama is state \"01\"). If these import as numeric, that leading zero may be lost. This means we need to go back to our import steps and *explicitly specify* how `read_csv()` should import these columns.\n\nWhen `read_csv()` initiates the process of reading data, it reads the first several rows of data that then makes an educated guess as to the format to use for each column of data. We can override this and explicitly tell `read_csv()` what format to use for particular columns using the `col_types` option. We specify column types by providing an equivalency statement. For instance `col_types = cols(TRTID10 = col_character())` would say please let me explicitly define a column type. Where a column is named \"TRTID10\", read in this column and assign it's contents as character. We could explicitly set other types as needed (e.g. col_numeric(), col_boolean(), etc.).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_1970<-read_csv(\"08_neighborhood_change/data_raw/LTDB_Std_1970_fullcount.csv\", col_types = cols(TRTID10 = col_character()))\nS_1970<-read_csv(\"08_neighborhood_change/data_raw/ltdb_std_1970_sample.csv\", col_types = cols(TRTID10 = col_character()))\n\nF_1980<-read_csv(\"08_neighborhood_change/data_raw/LTDB_Std_1980_fullcount.csv\", col_types = cols(TRTID10 = col_character()))\nS_1980<-read_csv(\"08_neighborhood_change/data_raw/ltdb_std_1980_sample.csv\", col_types = cols(trtid10 = col_character()))\n\nF_1990<-read_csv(\"08_neighborhood_change/data_raw/LTDB_Std_1990_fullcount.csv\", col_types = cols(TRTID10 = col_character()))\nS_1990<-read_csv(\"08_neighborhood_change/data_raw/ltdb_std_1990_sample.csv\", col_types = cols(TRTID10 = col_character()))\n\nF_2000<-read_csv(\"08_neighborhood_change/data_raw/LTDB_Std_2000_fullcount.csv\", col_types = cols(TRTID10 = col_character()))\nS_2000<-read_csv(\"08_neighborhood_change/data_raw/ltdb_std_2000_sample.csv\", col_types = cols(TRTID10 = col_character()))\n\nF_2010<-read_csv(\"08_neighborhood_change/data_raw/LTDB_Std_2010_fullcount.csv\", col_types = cols(tractid = col_character()))\nS_2010<-read_csv(\"08_neighborhood_change/data_raw/LTDB_std_200812_Sample.csv\", col_types = cols(tractid = col_character()))\n\nF_2020<-read_csv(\"08_neighborhood_change/data_raw/LTDB_Std_2020_fullcount.csv\", col_types = cols(TRTID2010 = col_character()))\nS_2020<-read_csv(\"08_neighborhood_change/data_raw/LTDB_std_201519_Sample.csv\", col_types = cols(tractid = col_character()))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nF_1970<-read_csv(\"data_raw/LTDB_Std_1970_fullcount.csv\", col_types = cols(TRTID10=col_character()))\nS_1970<-read_csv(\"data_raw/ltdb_std_1970_sample.csv\", col_types = cols(TRTID10=col_character()))\n\n# Finish (re)importing the LTDB data here.\n\nF_1980<-read_csv(\"data_raw/LTDB_Std_1980_fullcount.csv\", col_types = cols(TRTID10=col_character()))\nS_1980<-read_csv(\"data_raw/ltdb_std_1980_sample.csv\", col_types = cols(trtid10=col_character()))\n\nF_1990<-read_csv(\"data_raw/LTDB_Std_1990_fullcount.csv\", col_types = cols(TRTID10=col_character()))\nS_1990<-read_csv(\"data_raw/ltdb_std_1990_sample.csv\", col_types = cols(TRTID10=col_character()))\n\nF_2000<-read_csv(\"data_raw/LTDB_Std_2000_fullcount.csv\", col_types = cols(TRTID10=col_character()))\nS_2000<-read_csv(\"data_raw/ltdb_std_2000_sample.csv\", col_types = cols(TRTID10=col_character()))\n\nF_2010<-read_csv(\"data_raw/LTDB_Std_2010_fullcount.csv\", col_types = cols(tractid=col_character()))\nS_2010<-read_csv(\"data_raw/LTDB_std_200812_Sample.csv\", col_types = cols(tractid=col_character()))\n\nF_2020<-read_csv(\"data_raw/LTDB_Std_2020_fullcount.csv\", col_types = cols(tractid=col_character()))\nS_2020<-read_csv(\"data_raw/LTDB_std_201519_Sample.csv\", col_types = cols(tractid=col_character()))\n```\n:::\n\n\nThen we can go ahead and pull out our income columns as we did before:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninc_70<-S_1970 |> select(TRTID10, INCPC70)\ninc_80<-S_1980 |> select(TRTID10 = trtid10, incpc80)\ninc_90<-S_1990 |> select(TRTID10, INCPC90)\ninc_00<-S_2000 |> select(TRTID10, INCPC00)\ninc_10<-S_2010 |> select(TRTID10 = tractid, INCPC12 = incpc12)\ninc_20<-S_2020 |> select(TRTID10 = tractid, STATE = statea, COUNTY = countya, TRACT = tracta, INCPC19 = incpc19)\n```\n:::\n\n\nLet's run one more check on the TRTID10 columns. Lets chech the number of characters in out TRTID columns. Every combined state-county-tract FIPS code should be 11 characters long:\n\n-   2 state characters\n-   3 county characters\n-   6 tract characters\n\nLets take our inc_70 dataset, group it by the count of the number of characters in each observation in the TRTID10 column (`nchar()`), and then ciybt the number of observations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninc_70 |> \n  group_by(nchar(TRTID10)) |> \n  summarise(n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               10 11375\n2               11 41384\n```\n:::\n:::\n\n\nHmm - in the 1970 income data, we have 11,375 observations with less than the expected number of characters. Why might this be? This could be an artifact of the data we downloaded or could be a function of how `read_csv()` is importing these data.\n\nPast experience tells me that we are missing the leading zero from states with state FIPS codes under 10. We can easily add this back in using the `str_pad()` command from the *stringr* package - this package has tools for modifying strings or character vectors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninc_70<-inc_70 |> \n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\n```\n:::\n\n\nThe first part should be straightforward - we're overwriting the existing inc_70 data with an updated version. We're using `mutate()` to alter the TRTID10 column. We're using `str_pad()` to \"pad\" the TRTID10 column. The desired width (number of characters) is 11, we're going to add our pad to the left side of the existing string, and the pad we'll add is the character \"0\".\n\n`str_pad()` will add however many pad characters we need to get to the desired length. For instance, if we were padding a string \"123\" with \"A\" and specified a width of 5, we would get \"AA123\". If we applied the same to the string \"1536\" we would get \"A1536\". If we applied it to \"15683\" we would get \"15683\".\n\nNow we can check to confirm that this worked:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninc_70 |> \n  group_by(nchar(TRTID10)) |>  \n  summarise(n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               11 52759\n```\n:::\n:::\n\n\nAll the observations of TRTID10 are now 11 characters wide.\n\nCheck the 1980 to 2010 data, and pad where needed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninc_80 |> \n  group_by(nchar(TRTID10)) |>  \n  summarise(n()) # Needs padding\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               10 12353\n2               11 46834\n```\n:::\n\n```{.r .cell-code}\ninc_90 |>  \n  group_by(nchar(TRTID10)) |>  \n  summarise(n()) # Needs padding\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               10 13663\n2               11 59030\n```\n:::\n\n```{.r .cell-code}\ninc_00 |>  \n  group_by(nchar(TRTID10)) |>  \n  summarise(n()) # Needs padding\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               10 13663\n2               11 59030\n```\n:::\n\n```{.r .cell-code}\ninc_10 |>  \n  group_by(nchar(TRTID10)) |> \n  summarise(n()) # No padding needed\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               11 73056\n```\n:::\n\n```{.r .cell-code}\ninc_20 |>  \n  group_by(nchar(TRTID10)) |>  \n  summarise(n()) # No padding needed\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               11 73056\n```\n:::\n\n```{.r .cell-code}\ninc_80<-inc_80 |> \n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\ninc_90<-inc_90 |>  \n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\ninc_00<-inc_00 |>  \n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\n```\n:::\n\n\nNow confirm that your padding has worked:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninc_70 |> \n  group_by(nchar(TRTID10)) |> \n  summarise(n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               11 52759\n```\n:::\n\n```{.r .cell-code}\ninc_80 |>  \n  group_by(nchar(TRTID10)) |> \n  summarise(n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               11 59187\n```\n:::\n\n```{.r .cell-code}\ninc_90 |> \n  group_by(nchar(TRTID10)) |> \n  summarise(n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               11 72693\n```\n:::\n\n```{.r .cell-code}\ninc_00 |>  \n  group_by(nchar(TRTID10)) |>  \n  summarise(n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               11 72693\n```\n:::\n\n```{.r .cell-code}\ninc_10 |> \n  group_by(nchar(TRTID10)) |> \n  summarise(n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               11 73056\n```\n:::\n\n```{.r .cell-code}\ninc_20 |> \n  group_by(nchar(TRTID10)) |> \n  summarise(n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  `nchar(TRTID10)` `n()`\n             <int> <int>\n1               11 73056\n```\n:::\n:::\n\n\nNote that this padding issue would not effect Illinois (state FIPS code 17), but it's important to know how to diagnose and fix this problem, as it could come up for other states or places you are working with.\n\nRemember to take your time, and build code that you (or others) can use universally in the future.\n\n### Re-doing Data Import\n\nBefore we move forward, let's update our data import code so that we incorporate addressing the data issues we've covered into our data importation workflow. As a reminder, we need to rename our combined state-county-tract FIPS column and pad the column to 11 characters on the left size with \"0\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_1970<-read_csv(\"08_neighborhood_change/data_raw/LTDB_Std_1970_fullcount.csv\", col_types = cols(TRTID10 = col_character())) |> \n   mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\nS_1970<-read_csv(\"08_neighborhood_change/data_raw/ltdb_std_1970_sample.csv\", col_types = cols(TRTID10 = col_character())) |> \n   mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\n\nF_1980<-read_csv(\"08_neighborhood_change/data_raw/LTDB_Std_1980_fullcount.csv\", col_types = cols(TRTID10 = col_character())) |> \n   mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\nS_1980<-read_csv(\"08_neighborhood_change/data_raw/ltdb_std_1980_sample.csv\", col_types = cols(trtid10 = col_character())) |> \n   mutate(TRTID10 = str_pad(trtid10, width = 11, side=\"left\", pad= \"0\"))\n\nF_1990<-read_csv(\"08_neighborhood_change/data_raw/LTDB_Std_1990_fullcount.csv\", col_types = cols(TRTID10 = col_character())) |> \n   mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\nS_1990<-read_csv(\"08_neighborhood_change/data_raw/ltdb_std_1990_sample.csv\", col_types = cols(TRTID10 = col_character())) |> \n   mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\n\nF_2000<-read_csv(\"08_neighborhood_change/data_raw/LTDB_Std_2000_fullcount.csv\", col_types = cols(TRTID10 = col_character())) |> \n   mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\nS_2000<-read_csv(\"08_neighborhood_change/data_raw/ltdb_std_2000_sample.csv\", col_types = cols(TRTID10 = col_character())) |> \n   mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\n\nF_2010<-read_csv(\"08_neighborhood_change/data_raw/LTDB_Std_2010_fullcount.csv\", col_types = cols(tractid = col_character()))\nS_2010<-read_csv(\"08_neighborhood_change/data_raw/LTDB_std_200812_Sample.csv\", col_types = cols(tractid = col_character())) |> \n   rename(TRTID10 = tractid)\n\nF_2020<-read_csv(\"08_neighborhood_change/data_raw/LTDB_Std_2020_fullcount.csv\", col_types = cols(TRTID2010 = col_character()))\nS_2020<-read_csv(\"08_neighborhood_change/data_raw/LTDB_std_201519_Sample.csv\", col_types = cols(tractid = col_character())) |> \n   rename(TRTID10 = tractid)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nF_1970<-read_csv(\"data_raw/LTDB_Std_1970_fullcount.csv\", col_types = cols(TRTID10=col_character())) |>\n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\n\nS_1970<-read_csv(\"data_raw/ltdb_std_1970_sample.csv\", col_types = cols(TRTID10=col_character())) |>\n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\n\n# Finish (re)importing the LTDB data here.\n\nF_1980<-read_csv(\"data_raw/LTDB_Std_1980_fullcount.csv\", col_types = cols(TRTID10=col_character())) |>\n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\nS_1980<-read_csv(\"data_raw/ltdb_std_1980_sample.csv\", col_types = cols(trtid10=col_character())) |> \n  rename(TRTID10 = trtid10) |>\n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\n\nF_1990<-read_csv(\"data_raw/LTDB_Std_1990_fullcount.csv\", col_types = cols(TRTID10=col_character())) |>\n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\nS_1990<-read_csv(\"data_raw/ltdb_std_1990_sample.csv\", col_types = cols(TRTID10=col_character())) |>\n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\n\nF_2000<-read_csv(\"data_raw/LTDB_Std_2000_fullcount.csv\", col_types = cols(TRTID10=col_character())) |>\n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\nS_2000<-read_csv(\"data_raw/ltdb_std_2000_sample.csv\", col_types = cols(TRTID10=col_character())) |>\n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\n\nF_2010<-read_csv(\"data_raw/LTDB_Std_2010_fullcount.csv\", col_types = cols(tractid=col_character())) |>\n    rename(TRTID10 = tractid) |>\n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\nS_2010<-read_csv(\"data_raw/ltdb_std_2010_sample.csv\", col_types = cols(tractid=col_character())) |>\n      rename(TRTID10 = tractid) |>\n  mutate(TRTID10 = str_pad(TRTID10, width = 11, side=\"left\", pad= \"0\"))\n```\n:::\n\n\nAnd from here we can re-create the inc\\_\\[year\\] datasets:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninc_70<-S_1970 |>  \n  select(TRTID10, INCPC70)\ninc_80<-S_1980 |>  \n  select(TRTID10, INCPC80 = incpc80)\ninc_90<-S_1990 |>  \n  select(TRTID10, INCPC90)\ninc_00<-S_2000 |>  \n  select(TRTID10, INCPC00)\ninc_10<-S_2010 |>  \n  select(TRTID10, INCPC12 = incpc12)\ninc_20 <- S_2020 |> \n  select(TRTID10, STATE = statea, COUNTY = countya, TRACT = tracta, INCPC19 = incpc19)\n```\n:::\n\n\n### Join Together\n\nFinally we have our data in a form where we can join our income cross-sections together. Using left joins, join together your six income data cross-sections into a new dataset called income.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome<-left_join(inc_20, inc_10, by=\"TRTID10\")\nincome<-left_join(income, inc_00, by=\"TRTID10\")\nincome<-left_join(income, inc_90, by=\"TRTID10\")\nincome<-left_join(income, inc_80, by=\"TRTID10\")\nincome<-left_join(income, inc_70, by=\"TRTID10\")\n```\n:::\n\n\nRe-organize the income per capita fields so they are in the order 1970, 1980, 1990, 2000, 2010, 2010.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome<-income  |>  \n  select(TRTID10, STATE, COUNTY, TRACT, INCPC70, INCPC80, INCPC90, INCPC00, INCPC12, INCPC19)\n```\n:::\n\n\n### Adjust for Inflation\n\nWe have one more step to accomplish before we can move forward with analysis. Each of our income observations is reported out in the monetary value associated with the time period in which it was collected. Due to inflation, money has a different value over time - \\$5 in 1970 could buy you a lot more than it can in 2020. Using the [CPI Inflation Calculator](https://www.bls.gov/data/inflation_calculator.htm), we can calculate that the value of 5 dollars in 1970 would have the equivalent value of 39 dollars and 57 cents in 2023 dollars.\n\nBy standardizing all of the dollar values to their equivalent value in a common year, it is much easier to compare changes in income over time as they are in the same dollar equivalent unit.\n\nThe CPI Inflation Calculator can help us here. If we find out how much \\$1 in our data collection year is worth in a common current year, we can figure out what we'd have to multiply our observations by to convert them to current year dollars.\n\nWe will eventually add some additional data and demographic characteristics from the 2015-2019 ACS. Looking in the 2015-2019 ACS per capital income table [B19301: Per Capita Income in the Past 12 Months](https://data.census.gov/cedsci/table?q=B19301%3A%20PER%20CAPITA%20INCOME%20IN%20THE%20PAST%2012%20MONTHS%20%28IN%202019%20INFLATION-ADJUSTED%20DOLLARS%29&tid=ACSDT1Y2019.B19301&hidePreview=true) we see that these data are reported in inflation-adjusted 2019 dollars.\n\nSince 2019 will be our most recent point of reference, let's adjust our dollar values from 1970 - 2010 to 2019 dollars. Using the CPI Inflation Calculator, find the value of 1 dollar in January of each of the decennial years in January 2019.\n\n| Year        | Value |\n|-------------|-------|\n| 1970        | 6.66  |\n| 1980        | 3.24  |\n| 1990        | 1.98  |\n| 2000        | 1.49  |\n| 2010 (2012) | 1.11  |\n\nNow multiply each of the income per capita columns by their inflation adjustment factor to get them into 2019 dollars (assume 1970, 1980, 1990, and 2000 data are from January of that year, and our 2010 data which comes from the ACS is actually in 2012 dollars).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome<-income |> \n  mutate(\n  INCPC70 = INCPC70*6.66,\n  INCPC80 = INCPC80*3.24,\n  INCPC90 = INCPC90*1.98,\n  INCPC00 = INCPC00*1.49,\n  INCPC12 = INCPC12*1.11\n)\n```\n:::\n\n\nWe now have a relatively clean income dataset that we could use to analyze any tract, city, or region within the United States.\n\n## Select Regional Data\n\nAs we have for our last few analyses, we're going to examine neighborhood change for New York City. As in the past, we'll start by pulling out data for the counties that represent boroughs of New York City. Our LTDB data contains a combined State, County, Tract FIPS code - how could we pull out the state and county FIPS codes we would need to identify counties?\n\nWe have casually been introduced to stringr's `substr()` function in the past, that allows us to pull out substrings based upon the character positions. In this case, we want to pull out the first five characters from the TRTID10 field, which contains the combined state and county FIPS code. Use `substr()` inside a mutate()\\` to create a new column called COFIPS in our combined income dataset that contains the first five characters from TRTID10.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome<-income |> \n  mutate(COFIPS = substr(TRTID10, 0, 5))\n```\n:::\n\n\nAs a reminder, here's the names and FIPS codes for NYC Boroughs:\n\n| FIPS Code | County Name     | Borough Name  |\n|-----------|-----------------|---------------|\n| 36047     | Kings County    | Brooklyn      |\n| 36005     | Bronx County    | Bronx         |\n| 36081     | Queens County   | Queens        |\n| 36085     | Richmond County | Staten Island |\n| 36061     | New York County | Manhattan     |\n\nLet's create a new income dataset called \\_income that contains income observations for New York City's Boroughs (in your `filter()` statement consider using `%in%` with a list of combined state-county FIPS codes):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income <- income |> \n  filter(COFIPS %in% c(\"36047\", \"36005\", \"36081\", \"36085\", \"36061\"))\n```\n:::\n\n\nNow's a good time to check descriptive statistics for our income data. Let's use `summary()` on the chi_income object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(nyc_income)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   TRTID10             STATE              COUNTY             TRACT          \n Length:2167        Length:2167        Length:2167        Length:2167       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    INCPC70          INCPC80          INCPC90          INCPC00      \n Min.   :     0   Min.   :     0   Min.   :     0   Min.   :     0  \n 1st Qu.: 24115   1st Qu.: 15030   1st Qu.: 18831   1st Qu.: 18996  \n Median : 29101   Median : 21062   Median : 27186   Median : 25768  \n Mean   : 31049   Mean   : 22503   Mean   : 30743   Mean   : 32044  \n 3rd Qu.: 34249   3rd Qu.: 25867   3rd Qu.: 34583   3rd Qu.: 34538  \n Max.   :278792   Max.   :140026   Max.   :315848   Max.   :441085  \n NA's   :30       NA's   :15       NA's   :15       NA's   :15      \n    INCPC12            INCPC19          COFIPS         \n Min.   :   387.4   Min.   :  3341   Length:2167       \n 1st Qu.: 19782.1   1st Qu.: 22879   Class :character  \n Median : 26797.6   Median : 30120   Mode  :character  \n Mean   : 33951.3   Mean   : 38454                     \n 3rd Qu.: 36367.8   3rd Qu.: 41411                     \n Max.   :280727.9   Max.   :258909                     \n NA's   :47         NA's   :50                         \n```\n:::\n:::\n\n\nWe have 2,167 observations for New York City.\n\n# Tract-Region Income Comparisons\n\nBased upon the Voorhees Center's analysis, our next step is to calculate the difference between the income in each tract and the \"Metro Area Weighted Average Income\". Metro Area Average Income makes sense - this is the average of the income per capita for all census tracts in the metro area. *Weighted Average Income*, income requires just a bit more thought. If we were to find the *Average Income* for all tracts in the metro area, we would be assuming they all have the same population. Calculating the *Weighted Average Income* weights the contribution of each tract's income observation by the population in the census tract, so that tracts with more people will get more weight in the calculation of the average.\n\nThis means that we need to grab population data for each of our observation years, so that we can then combine the population data and our income data to produced weighted average income.\n\nLet's pull the population numbers from our full count data. Create a dataset called pop that joins the tract population from the POP\\_\\[year\\] column for each year into one dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npop_70<- F_1970 |> select(TRTID10, POP70)\npop_80<- F_1980 |> select(TRTID10, POP80)\npop_90<- F_1990 |> select(TRTID10, POP90)\npop_00<- F_2000 |> select(TRTID10, POP00)\npop_10<- F_2010 |> select(TRTID10 = tractid, POP10=pop10) # note the renaming of variables.\npop_20<- F_2020 |> select(TRTID10 = TRTID2010, POP20=pop20) # note the renaming of variables.\n\npop<-left_join(pop_20, pop_10, by=\"TRTID10\")\npop<-left_join(pop, pop_00, by=\"TRTID10\")\npop<-left_join(pop, pop_90, by=\"TRTID10\")\npop<-left_join(pop, pop_80, by=\"TRTID10\")\npop<-left_join(pop, pop_70, by=\"TRTID10\")\npop <- pop |> select(TRTID10, POP70, POP80, POP90, POP00, POP10, POP20)\n```\n:::\n\n\nNow that you have combined population data, join it to your NYC income data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income<-left_join(nyc_income, pop, by=\"TRTID10\")\n```\n:::\n\n\nNow we can calculate the weighted average - we create a new column for the weighted average for each year. We supply the income per capita information and then the weights (in this case, the population count). We also specify the removal of NA values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income<-nyc_income |> mutate(\n  winc_70 = weighted.mean(INCPC70, POP70, na.rm=TRUE),\n  winc_80 = weighted.mean(INCPC80, POP80, na.rm=TRUE),\n  winc_90 = weighted.mean(INCPC90, POP90, na.rm=TRUE),\n  winc_00 = weighted.mean(INCPC00, POP00, na.rm=TRUE),\n  winc_10 = weighted.mean(INCPC12, POP10, na.rm=TRUE),\n  winc_20 = weighted.mean(INCPC19, POP20, na.rm=TRUE)\n)\n```\n:::\n\n\nNow we can calculate the difference between each tract's income and the regional average income per capita. Place these differences in income into new columns dincome\\_\\[year\\]:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income<-nyc_income |> \n  mutate(\n  dincome_70 = INCPC70 - winc_70,\n  dincome_80 = INCPC80 - winc_80,\n  dincome_90 = INCPC90 - winc_90,\n  dincome_00 = INCPC00 - winc_00,\n  dincome_10 = INCPC12 - winc_10,\n  dincome_20 = INCPC19 - winc_20\n)\n```\n:::\n\n\nAnd finally, we can calculate the percentage difference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income<-nyc_income |> \n  mutate(\n  pincome_70 = dincome_70/winc_70,\n  pincome_80 = dincome_80/winc_80,\n  pincome_90 = dincome_90/winc_90,\n  pincome_00 = dincome_00/winc_00,\n  pincome_10 = dincome_10/winc_10,\n  pincome_20 = dincome_20/winc_20\n)\n```\n:::\n\n\nRecall that the Voorhees Center's study classifies tracts based upon the percentage change:\n\n-   **Very High Income:** Greater than 40% above the regional average\n-   **High Income:** 20% - 40% above the regional average\n-   **Middle Income:** 20% below to 20% above the regional average\n-   **Low Income:** 20% below to 40% below the regional average\n-   **Very Low Income:** Greater than 40% below the regional average\n\nWe can then reshape our \"wide\" data into \"long\" data pulling out our percent change estimates:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income_long<-nyc_income |> \n  pivot_longer(pincome_70:pincome_20) |> \n  select(TRTID10, COUNTY, name, value)\n```\n:::\n\n\nRename the name and value columns\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income_long<-nyc_income_long |> \n  select(TRTID10, COUNTY, Year = name, pincome = value)\n```\n:::\n\n\nRe-label the years\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income_long<-nyc_income_long |> \n  mutate(Year = case_when(\n  Year == \"pincome_70\" ~ \"1970\",\n  Year == \"pincome_80\" ~ \"1980\",\n  Year == \"pincome_90\" ~ \"1990\",\n  Year == \"pincome_00\" ~ \"2000\",\n  Year == \"pincome_10\" ~ \"2010\",\n  Year == \"pincome_20\" ~ \"2020\"))\n```\n:::\n\n\nAnd use `case_when()` to label the percentage change values using the labels in the Voorhees Center report:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income_long<-nyc_income_long |> \n  mutate(pincome_cat = case_when(\n    between(pincome, -100, -.4) ~ \"Very Low Income\",\n    between(pincome, -.4, -.2) ~ \"Low Income\",\n    between(pincome, -.2, .2) ~ \"Middle Income\",\n    between(pincome, .2, .4) ~ \"High Income\",\n    between(pincome, .4, 100) ~ \"Very High Income\"\n  ))\n```\n:::\n\n\nWe're using `case_when()` to find the values in the pre-specified ranges, and then assigning them labels. `between()` conducts a logical test to see whether values fall within a range specified. In the case of \"Very Low Income\" and \"Very High Income\" we use really large values to specify the outer bounds that should capture all the values above of below 40 percent.\n\nLet's go ahead and count by each year the distribution of values in each category:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income_long |> \n  group_by(Year, pincome_cat) |> \n  summarise(count = n()) |> \n  pivot_wider(names_from = Year, values_from = count) |> \n  gt()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'Year'. You can override using the\n`.groups` argument.\n```\n:::\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"qxaokplxlp\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#qxaokplxlp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qxaokplxlp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qxaokplxlp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qxaokplxlp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qxaokplxlp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qxaokplxlp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qxaokplxlp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qxaokplxlp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qxaokplxlp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qxaokplxlp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qxaokplxlp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qxaokplxlp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qxaokplxlp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qxaokplxlp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qxaokplxlp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qxaokplxlp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qxaokplxlp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qxaokplxlp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qxaokplxlp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qxaokplxlp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qxaokplxlp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qxaokplxlp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qxaokplxlp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qxaokplxlp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qxaokplxlp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qxaokplxlp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qxaokplxlp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qxaokplxlp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qxaokplxlp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qxaokplxlp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qxaokplxlp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qxaokplxlp .gt_left {\n  text-align: left;\n}\n\n#qxaokplxlp .gt_center {\n  text-align: center;\n}\n\n#qxaokplxlp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qxaokplxlp .gt_font_normal {\n  font-weight: normal;\n}\n\n#qxaokplxlp .gt_font_bold {\n  font-weight: bold;\n}\n\n#qxaokplxlp .gt_font_italic {\n  font-style: italic;\n}\n\n#qxaokplxlp .gt_super {\n  font-size: 65%;\n}\n\n#qxaokplxlp .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#qxaokplxlp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qxaokplxlp .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qxaokplxlp .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qxaokplxlp .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qxaokplxlp .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qxaokplxlp .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">pincome_cat</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">1970</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">1980</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">1990</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">2000</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">2010</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">2020</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">High Income</td>\n<td class=\"gt_row gt_right\">169</td>\n<td class=\"gt_row gt_right\">149</td>\n<td class=\"gt_row gt_right\">127</td>\n<td class=\"gt_row gt_right\">113</td>\n<td class=\"gt_row gt_right\">106</td>\n<td class=\"gt_row gt_right\">82</td></tr>\n    <tr><td class=\"gt_row gt_left\">Low Income</td>\n<td class=\"gt_row gt_right\">376</td>\n<td class=\"gt_row gt_right\">389</td>\n<td class=\"gt_row gt_right\">398</td>\n<td class=\"gt_row gt_right\">528</td>\n<td class=\"gt_row gt_right\">529</td>\n<td class=\"gt_row gt_right\">566</td></tr>\n    <tr><td class=\"gt_row gt_left\">Middle Income</td>\n<td class=\"gt_row gt_right\">1192</td>\n<td class=\"gt_row gt_right\">922</td>\n<td class=\"gt_row gt_right\">829</td>\n<td class=\"gt_row gt_right\">636</td>\n<td class=\"gt_row gt_right\">597</td>\n<td class=\"gt_row gt_right\">558</td></tr>\n    <tr><td class=\"gt_row gt_left\">Very High Income</td>\n<td class=\"gt_row gt_right\">192</td>\n<td class=\"gt_row gt_right\">222</td>\n<td class=\"gt_row gt_right\">234</td>\n<td class=\"gt_row gt_right\">249</td>\n<td class=\"gt_row gt_right\">263</td>\n<td class=\"gt_row gt_right\">281</td></tr>\n    <tr><td class=\"gt_row gt_left\">Very Low Income</td>\n<td class=\"gt_row gt_right\">208</td>\n<td class=\"gt_row gt_right\">470</td>\n<td class=\"gt_row gt_right\">564</td>\n<td class=\"gt_row gt_right\">626</td>\n<td class=\"gt_row gt_right\">625</td>\n<td class=\"gt_row gt_right\">630</td></tr>\n    <tr><td class=\"gt_row gt_left\">NA</td>\n<td class=\"gt_row gt_right\">30</td>\n<td class=\"gt_row gt_right\">15</td>\n<td class=\"gt_row gt_right\">15</td>\n<td class=\"gt_row gt_right\">15</td>\n<td class=\"gt_row gt_right\">47</td>\n<td class=\"gt_row gt_right\">50</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nWe used `pivot_wider()` here to make each year into a column and specify that values were coming from the count of census tracts (it will assume that any remaining columns are our identity columns, in this case, the income category).\n\nCan you see anything immediately from this table? If you look at middle income tracts, we see a decline in the number. We see more tracts transitioning to the extremes - very high income or very low income.\n\nThis is already getting interesting. This also corresponds with one of the main findings highlighted by the Voorhees Center:\n\n> As illustrated by our research, between the nearly fifty-year time period, poverty and wealth has substantially increased while middle-income earning populations have largely declined.\n\nBefore we move forward, we can take care of one more technical thing and remove the raw data we worked with using `rm()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(F_1970, F_1980, F_1990, F_2000, F_2010, F_2020, S_1970, S_1980, S_1990, S_2000, S_2010, S_2020, inc_70, inc_80, inc_90, inc_00, inc_10, inc_20, pop_70, pop_80, pop_90, pop_00, pop_10, pop_20, income, pop)\n```\n:::\n\n\n# Completing Our Time Series\n\nWe currently have data from 1970, 1980, 1990, 2000, 2010 (2012 ACS), and 2020 (2019 ACS). Let's also create indicators comparable to what is in the Who Can Live in Chicago? Report: Race, Age, Disability, Housing, and Employment.\n\n-   **Race:** Race and Ethnicity (Percent White, Black, Asian, Other, Latinx)\n-   **Age:** Age structure\n-   **Disability:** Population with a disability\n-   **Housing:** Housing tenure (own vs. rent), Housing cost burden (% households paying \\> 30% income towards rent)\n-   **Employment:** Unemployment, Labor Force Participation, Occupation\n\n| Census Table                                                                                                                                                                                                                                             | Description               | Indicators to Construct                                   |\n|-------------------|-------------------|----------------------------------|\n| [B03002](https://data.census.gov/cedsci/table?q=ethnicity&y=2019&d=ACS%205-Year%20Estimates%20Detailed%20Tables&tid=ACSDT5Y2019.B03002)                                                                                                                  | Race and Ethnicity        | \\% White, % Black, % Asian, % Other, % Latinx (all races) |\n| [B01001](https://data.census.gov/cedsci/table?q=B01001&y=2019&d=ACS%205-Year%20Estimates%20Detailed%20Tables&tid=ACSDT5Y2019.B01001)                                                                                                                     | Age Structure             | Age 0-19, Age 20-34, Age 35-64, Age 65 up                 |\n| [B18101](https://data.census.gov/cedsci/table?q=age&y=2019&d=ACS%205-Year%20Estimates%20Detailed%20Tables&tid=ACSDT5Y2019.B01001https://data.census.gov/cedsci/table?q=age&y=2019&d=ACS%205-Year%20Estimates%20Detailed%20Tables&tid=ACSDT5Y2019.B01001) | Disability Status         | \\% Disabled                                               |\n| [B25003](https://data.census.gov/cedsci/table?q=Owner%2FRenter%20%28Tenure%29&y=2019&d=ACS%205-Year%20Estimates%20Detailed%20Tables&tid=ACSDT5Y2019.B25003&hidePreview=false)                                                                            | Housing Tenure            | \\% Renter, % Owner                                        |\n| [B25106](https://data.census.gov/cedsci/table?q=housing%20cost&y=2019&d=ACS%205-Year%20Estimates%20Detailed%20Tables&tid=ACSDT5Y2019.B25106&hidePreview=false)                                                                                           | Housing Cost Burden       | \\% Housing Cost Burdened (owners and renters)             |\n| [B23025](https://data.census.gov/cedsci/table?q=labor%20force&y=2019&d=ACS%205-Year%20Estimates%20Detailed%20Tables&tid=ACSDT5Y2019.B23025&hidePreview=false)                                                                                            | Unemployment              | \\% Unemployed                                             |\n| [B23025](https://data.census.gov/cedsci/table?q=labor%20force&y=2019&d=ACS%205-Year%20Estimates%20Detailed%20Tables&tid=ACSDT5Y2019.B23025&hidePreview=false)                                                                                            | Labor Force Participation | \\% In the Labor Force                                     |\n| [C24050](https://data.census.gov/cedsci/table?q=employment%20by%20industry&y=2019&d=ACS%205-Year%20Estimates%20Detailed%20Tables&tid=ACSDT5Y2019.C24050&hidePreview=false)                                                                               | Employment by Industry    |                                                           |\n\n### Race and Ethnicity\n\nWhile you're at it, be sure to download population data so you can calculate weighted regional averages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacs_race<-get_acs(geography = \"tract\", state = \"NY\", variables = c(\"B03002_001\", \"B03002_003\", \"B03002_004\", \"B03002_006\", \"B03002_012\"), year = 2019, survey = \"acs5\", output = \"wide\")  |> \n  mutate(\n  P_White = B03002_003E/B03002_001E,\n  P_Black = B03002_004E/B03002_001E,\n  P_Asian = B03002_006E/B03002_001E,\n  P_Latinx = B03002_012E/B03002_001E,\n  P_Other = (B03002_001E - B03002_003E - B03002_004E - B03002_006E - B03002_012E)/B03002_001E\n) |> select(GEOID, POP19 = B03002_001E, P_White, P_Black, P_Asian, P_Latinx, P_Other)\n```\n:::\n\n\n### Age Structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacs_age<-get_acs(geography = \"tract\", state = \"NY\", table = c(\"B01001\"), year = 2019, survey = \"acs5\", output = \"wide\") |> mutate(\n  Age_00_19 = B01001_003E+B01001_004E+B01001_005E+B01001_006E+B01001_007E + B01001_027E+B01001_028E+B01001_029E+B01001_030E+B01001_031E,\n  Age_20_34 = B01001_008E+B01001_009E+B01001_010E+B01001_011E+B01001_012E+B01001_032E +B01001_033E + B01001_034E + B01001_035E+ B01001_036E,\n  Age_35_64 = B01001_013E +B01001_014E + B01001_015E + B01001_016E + B01001_017E + B01001_018E + B01001_019E + B01001_037E + B01001_038E + B01001_039E + B01001_040E+B01001_041E+B01001_042E+B01001_043E,\n  Age_65up = B01001_020E + B01001_021E + B01001_022E + B01001_023E + B01001_024E +B01001_025E + B01001_044E + B01001_045E + B01001_046E + B01001_047E + B01001_048E +B01001_049E\n) |> select(GEOID, Age_00_19, Age_20_34, Age_35_64, Age_65up)\n```\n:::\n\n\n### Disability Status\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacs_disability<-get_acs(geography = \"tract\", state = \"NY\", table = c(\"B18101\"), year = 2019, survey = \"acs5\", output = \"wide\")  |> mutate(\n  P_Disabled = (B18101_004E + B18101_007E + B18101_010E+B18101_013E+B18101_016E+B18101_019E+B18101_023E+B18101_026E+B18101_029E+B18101_032E+B18101_035E+B18101_038E)/B18101_001E\n  ) |> select(GEOID, P_Disabled)\n```\n:::\n\n\n### Housing Tenure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacs_tenure<-get_acs(geography = \"tract\", state = \"NY\", table = c(\"B25003\"), year = 2019, survey = \"acs5\", output = \"wide\")  |> mutate(\n  P_Own =B25003_002E/B25003_001E,\n  P_Rent = B25003_003E/B25003_001E) |> select(GEOID, P_Own, P_Rent)\n```\n:::\n\n\n### Housing Cost Burden\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacs_cost<-get_acs(geography = \"tract\", state = \"NY\", table = c(\"B25106\"), year = 2019, survey = \"acs5\", output = \"wide\")  |> mutate(\n  P_CostBurden = (B25106_006E + B25106_010E +B25106_014E + B25106_018E + B25106_022E + B25106_028E + B25106_032E + B25106_036E + B25106_040E+B25106_044E)/B25106_001E\n) |> select(GEOID, P_CostBurden)\n```\n:::\n\n\n### Labor Force Participation / Unemployment\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacs_labor<-get_acs(geography = \"tract\", state = \"NY\", table = c(\"B23025\"), year = 2019, survey = \"acs5\", output = \"wide\")  |> mutate(\n  P_Unemp = B23025_005E/B23025_002E,\n  P_LabForce = B23025_002E/B23025_001E\n) |> select(GEOID, P_Unemp, P_LabForce)\n```\n:::\n\n\n### Employment by Industry\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacs_employment<-get_acs(geography = \"tract\", state = \"NY\", table = c(\"C24050\"), year = 2019, survey = \"acs5\", output = \"wide\")  |> mutate(P_Emp_Ag = C24050_002E/C24050_001E,\nP_Emp_Const = C24050_003E/C24050_001E,\nP_Emp_Manuf = C24050_004E/C24050_001E,\nP_Emp_Wholesale = C24050_005E/C24050_001E,\nP_Emp_Retail = C24050_006E/C24050_001E,\nP_Emp_Transportation = C24050_007E / C24050_001E,\nP_Emp_Information = C24050_008E / C24050_001E,\nP_Emp_FIRE = C24050_009E / C24050_001E,\nP_Emp_Management = C24050_010E / C24050_001E,\nP_Emp_Education = C24050_011E / C24050_001E,\nP_Emp_Arts = C24050_012E / C24050_001E,\nP_Emp_Other = C24050_013E / C24050_001E,\nP_Emp_PA = C24050_014E / C24050_001E\n) |> select(GEOID, P_Emp_Ag, P_Emp_Const, P_Emp_Manuf, P_Emp_Wholesale, P_Emp_Retail, P_Emp_Transportation, P_Emp_FIRE, P_Emp_Management, P_Emp_Education,P_Emp_Arts, P_Emp_Other, P_Emp_PA)\n```\n:::\n\n\n### Join ACS Data\n\nNow that we've downloaded your 2019 5-year ACS data, let's join the downloaded tables together. We will ultimately join this to our other income data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacs_19<-left_join(acs_age, acs_cost, by=\"GEOID\")\nacs_19<-left_join(acs_19, acs_disability, by=\"GEOID\")\nacs_19<-left_join(acs_19, acs_employment, by=\"GEOID\")\nacs_19<-left_join(acs_19, acs_labor, by=\"GEOID\")\nacs_19<-left_join(acs_19, acs_race, by=\"GEOID\")\nacs_19<-left_join(acs_19, acs_tenure, by=\"GEOID\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(acs_age, acs_cost, acs_disability, acs_employment, acs_labor, acs_race, acs_tenure)\n```\n:::\n\n\n## Moving Forward with our Three Cities Analysis\n\n### Join ACS Data to our Income Data\n\nLet's next join our \"new\" ACS data to our prior income data. Let's join to our chi_income (as opposed to chi_income_long data):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income <- left_join(nyc_income, acs_19, by=c(\"TRTID10\" = \"GEOID\"))\n```\n:::\n\n\n### Re-Create Income Categories in Wide-Format data\n\nPreviously, we created income category labels in our long-format version of the nyc_income data. This time, let's do the same thing in the wide format data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income<-nyc_income |> \n  mutate(\n    pincome_70 = case_when(\n    between(pincome_70, -100, -.4) ~ \"Very Low Income\",\n    between(pincome_70, -.4, -.2) ~ \"Low Income\",\n    between(pincome_70, -.2, .2) ~ \"Middle Income\",\n    between(pincome_70, .2, .4) ~ \"High Income\",\n    between(pincome_70, .4, 100) ~ \"Very High Income\"\n  ),\n  pincome_80 = case_when(\n    between(pincome_80, -100, -.4) ~ \"Very Low Income\",\n    between(pincome_80, -.4, -.2) ~ \"Low Income\",\n    between(pincome_80, -.2, .2) ~ \"Middle Income\",\n    between(pincome_80, .2, .4) ~ \"High Income\",\n    between(pincome_80, .4, 100) ~ \"Very High Income\"\n  ),\n    pincome_90 = case_when(\n    between(pincome_90, -100, -.4) ~ \"Very Low Income\",\n    between(pincome_90, -.4, -.2) ~ \"Low Income\",\n    between(pincome_90, -.2, .2) ~ \"Middle Income\",\n    between(pincome_90, .2, .4) ~ \"High Income\",\n    between(pincome_90, .4, 100) ~ \"Very High Income\"\n  ),\n    pincome_00 = case_when(\n    between(pincome_00, -100, -.4) ~ \"Very Low Income\",\n    between(pincome_00, -.4, -.2) ~ \"Low Income\",\n    between(pincome_00, -.2, .2) ~ \"Middle Income\",\n    between(pincome_00, .2, .4) ~ \"High Income\",\n    between(pincome_00, .4, 100) ~ \"Very High Income\"\n  ),\n    pincome_10 = case_when(\n    between(pincome_10, -100, -.4) ~ \"Very Low Income\",\n    between(pincome_10, -.4, -.2) ~ \"Low Income\",\n    between(pincome_10, -.2, .2) ~ \"Middle Income\",\n    between(pincome_10, .2, .4) ~ \"High Income\",\n    between(pincome_10, .4, 100) ~ \"Very High Income\"\n  ),\n    pincome_20 = case_when(\n    between(pincome_20, -100, -.4) ~ \"Very Low Income\",\n    between(pincome_20, -.4, -.2) ~ \"Low Income\",\n    between(pincome_20, -.2, .2) ~ \"Middle Income\",\n    between(pincome_20, .2, .4) ~ \"High Income\",\n    between(pincome_20, .4, 100) ~ \"Very High Income\"\n  )\n)\n```\n:::\n\n\n### Calculate Three Cities Categories\n\nIf you look on the \"Three Cities\" tab on the Voorhees website, you'll note that they separate tracts based upon the change in income between 1970 and the most recent time period (they use 2016 but we'll use 2019). Let's go ahead and calculate that change as well as the categorization of each census tract:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income<-nyc_income |> \n  mutate(pchange_70.19 = (INCPC19 - INCPC70)/INCPC70)\n```\n:::\n\n\nAnd once we calculate this, we can assign each tract to which \"City\" it belongs to based upon the change in income between 1970 and 2019:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income<-nyc_income |> \n  mutate(change_cat_70.19 = case_when(\n    between(pchange_70.19, .2, 100) ~ \"City 1 - Growing\",\n    between(pchange_70.19, -.2, .2) ~ \"City 2 - Middle\",\n    between(pchange_70.19,  -100, -.2) ~ \"City 3 - Shrinking\",\n    is.na(pchange_70.19) == \"TRUE\" ~ \"Uncategorized\",\n    pchange_70.19 == Inf ~ \"Uncategorized\")\n  )\n```\n:::\n\n\nWe have a small proportion of tracts which are ultimately not characterized because they are missing data for either 1970 or 2020. We can label these as uncategorized so that we can compare them and understand how they may be different from tracts whoch area assigned to a change type.\n\nWith this done, we can now develop some descriptives to help us understand differences between our three cities.\n\n## Describing Out Three Cities\n\nFollowing the descriptions provided on the Voorhees Center's [three cities study site](https://voorheescenter.uic.edu/chicago_communities/), let's systematically describe New York's neighborhoods based upon change in income.\n\n### How Many Tracts? How Many People?\nLooking at the first tab in the Voorhees report, we need to describe how many tracts and how many people fall within each city.\n\n![](08_neighborhood_change/images/03_NVC_Three_Cities.png)\nStart by counting how many tracts there are in each city and how many people lived in each city in 2019. Use `group_by()` and `summarise()` to accomplish this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income |> \n  group_by(change_cat_70.19) |> \n  summarise(Tracts = n(), Population = sum(POP19, na.rm=TRUE)) |> \n  gt() |> \n  fmt_number(3, decimals = 0)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"otbteeafzr\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#otbteeafzr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#otbteeafzr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#otbteeafzr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#otbteeafzr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#otbteeafzr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#otbteeafzr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#otbteeafzr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#otbteeafzr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#otbteeafzr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#otbteeafzr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#otbteeafzr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#otbteeafzr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#otbteeafzr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#otbteeafzr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#otbteeafzr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#otbteeafzr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#otbteeafzr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#otbteeafzr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#otbteeafzr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#otbteeafzr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#otbteeafzr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#otbteeafzr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#otbteeafzr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#otbteeafzr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#otbteeafzr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#otbteeafzr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#otbteeafzr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#otbteeafzr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#otbteeafzr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#otbteeafzr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#otbteeafzr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#otbteeafzr .gt_left {\n  text-align: left;\n}\n\n#otbteeafzr .gt_center {\n  text-align: center;\n}\n\n#otbteeafzr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#otbteeafzr .gt_font_normal {\n  font-weight: normal;\n}\n\n#otbteeafzr .gt_font_bold {\n  font-weight: bold;\n}\n\n#otbteeafzr .gt_font_italic {\n  font-style: italic;\n}\n\n#otbteeafzr .gt_super {\n  font-size: 65%;\n}\n\n#otbteeafzr .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#otbteeafzr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#otbteeafzr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#otbteeafzr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#otbteeafzr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#otbteeafzr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#otbteeafzr .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">change_cat_70.19</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Tracts</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Population</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">City 1 - Growing</td>\n<td class=\"gt_row gt_right\">678</td>\n<td class=\"gt_row gt_right\">2,824,154</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 2 - Middle</td>\n<td class=\"gt_row gt_right\">971</td>\n<td class=\"gt_row gt_right\">3,543,062</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 3 - Shrinking</td>\n<td class=\"gt_row gt_right\">453</td>\n<td class=\"gt_row gt_right\">2,009,535</td></tr>\n    <tr><td class=\"gt_row gt_left\">Uncategorized</td>\n<td class=\"gt_row gt_right\">65</td>\n<td class=\"gt_row gt_right\">42,565</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\nWe can see the split in 2019 population between growing, middle and shrinking places. We have 65 tracts which are unclassified with a population of around 42,565.\n\n### Race\nThe next pane in the Voorhees analysis summarizes each city based upon it's racial composition:\n\n![](08_neighborhood_change/images/05_Race.png)\n\nLet's develop a table that does the same:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income |> \n  group_by(change_cat_70.19) |> \n  summarise(\nTracts = n(), \nPWhite = mean(P_White, na.rm=TRUE),\nPBlack = mean(P_Black, na.rm=TRUE),\nPAsian = mean(P_Asian, na.rm=TRUE),\nPLatinx = mean(P_Latinx, na.rm=TRUE),\nPOther = mean(P_Other, na.rm=TRUE)\n) |> \n  gt() |> \n  fmt_percent(3:7, decimals = 1)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"nipcyapxij\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#nipcyapxij .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nipcyapxij .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nipcyapxij .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nipcyapxij .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nipcyapxij .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nipcyapxij .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nipcyapxij .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nipcyapxij .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nipcyapxij .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nipcyapxij .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nipcyapxij .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nipcyapxij .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nipcyapxij .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nipcyapxij .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nipcyapxij .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nipcyapxij .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nipcyapxij .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nipcyapxij .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nipcyapxij .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nipcyapxij .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nipcyapxij .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nipcyapxij .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nipcyapxij .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nipcyapxij .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nipcyapxij .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nipcyapxij .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nipcyapxij .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nipcyapxij .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nipcyapxij .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nipcyapxij .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nipcyapxij .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nipcyapxij .gt_left {\n  text-align: left;\n}\n\n#nipcyapxij .gt_center {\n  text-align: center;\n}\n\n#nipcyapxij .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nipcyapxij .gt_font_normal {\n  font-weight: normal;\n}\n\n#nipcyapxij .gt_font_bold {\n  font-weight: bold;\n}\n\n#nipcyapxij .gt_font_italic {\n  font-style: italic;\n}\n\n#nipcyapxij .gt_super {\n  font-size: 65%;\n}\n\n#nipcyapxij .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#nipcyapxij .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nipcyapxij .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nipcyapxij .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nipcyapxij .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nipcyapxij .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nipcyapxij .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">change_cat_70.19</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Tracts</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">PWhite</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">PBlack</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">PAsian</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">PLatinx</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">POther</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">City 1 - Growing</td>\n<td class=\"gt_row gt_right\">678</td>\n<td class=\"gt_row gt_right\">49.3%</td>\n<td class=\"gt_row gt_right\">17.4%</td>\n<td class=\"gt_row gt_right\">10.7%</td>\n<td class=\"gt_row gt_right\">19.5%</td>\n<td class=\"gt_row gt_right\">3.1%</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 2 - Middle</td>\n<td class=\"gt_row gt_right\">971</td>\n<td class=\"gt_row gt_right\">27.9%</td>\n<td class=\"gt_row gt_right\">28.0%</td>\n<td class=\"gt_row gt_right\">15.1%</td>\n<td class=\"gt_row gt_right\">25.5%</td>\n<td class=\"gt_row gt_right\">3.5%</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 3 - Shrinking</td>\n<td class=\"gt_row gt_right\">453</td>\n<td class=\"gt_row gt_right\">16.1%</td>\n<td class=\"gt_row gt_right\">20.6%</td>\n<td class=\"gt_row gt_right\">18.4%</td>\n<td class=\"gt_row gt_right\">42.0%</td>\n<td class=\"gt_row gt_right\">2.8%</td></tr>\n    <tr><td class=\"gt_row gt_left\">Uncategorized</td>\n<td class=\"gt_row gt_right\">65</td>\n<td class=\"gt_row gt_right\">30.9%</td>\n<td class=\"gt_row gt_right\">38.2%</td>\n<td class=\"gt_row gt_right\">4.2%</td>\n<td class=\"gt_row gt_right\">25.9%</td>\n<td class=\"gt_row gt_right\">0.8%</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\nWe might also want to revisit our based LTDB data so that we can describe change in racial composition for each city over time.\n\n### Age\n\nWe will next summarize each of the three cities by their age composition. Consider calculating percentages in addition to reporting the population counts.\n\n![](08_neighborhood_change/images/06_Age.png)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income |> \n  group_by(change_cat_70.19) |> \n  summarise(\nTracts = n(), \nPopTot = sum(POP19, na.rm=TRUE),\nAge_00_19 = sum(Age_00_19, na.rm=TRUE)/sum(POP19, na.rm=TRUE),\nAge_20_34 = sum(Age_20_34, na.rm=TRUE)/sum(POP19, na.rm=TRUE),\nAge_35_64 = sum(Age_35_64, na.rm=TRUE)/sum(POP19, na.rm=TRUE),\nAge_65up = sum(Age_65up, na.rm=TRUE)/sum(POP19, na.rm=TRUE)\n) |> \n  gt() |> \n  fmt_number(2:3, decimals = 0) |> \n  fmt_percent(4:7, decimals = 1)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"yvzrtllgun\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#yvzrtllgun .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yvzrtllgun .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yvzrtllgun .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yvzrtllgun .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yvzrtllgun .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yvzrtllgun .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yvzrtllgun .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yvzrtllgun .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yvzrtllgun .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yvzrtllgun .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yvzrtllgun .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yvzrtllgun .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yvzrtllgun .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yvzrtllgun .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yvzrtllgun .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yvzrtllgun .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yvzrtllgun .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yvzrtllgun .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yvzrtllgun .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yvzrtllgun .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yvzrtllgun .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yvzrtllgun .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yvzrtllgun .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yvzrtllgun .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yvzrtllgun .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yvzrtllgun .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yvzrtllgun .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yvzrtllgun .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yvzrtllgun .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yvzrtllgun .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yvzrtllgun .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yvzrtllgun .gt_left {\n  text-align: left;\n}\n\n#yvzrtllgun .gt_center {\n  text-align: center;\n}\n\n#yvzrtllgun .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yvzrtllgun .gt_font_normal {\n  font-weight: normal;\n}\n\n#yvzrtllgun .gt_font_bold {\n  font-weight: bold;\n}\n\n#yvzrtllgun .gt_font_italic {\n  font-style: italic;\n}\n\n#yvzrtllgun .gt_super {\n  font-size: 65%;\n}\n\n#yvzrtllgun .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#yvzrtllgun .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yvzrtllgun .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yvzrtllgun .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yvzrtllgun .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yvzrtllgun .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yvzrtllgun .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">change_cat_70.19</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Tracts</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">PopTot</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Age_00_19</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Age_20_34</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Age_35_64</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Age_65up</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">City 1 - Growing</td>\n<td class=\"gt_row gt_right\">678</td>\n<td class=\"gt_row gt_right\">2,824,154</td>\n<td class=\"gt_row gt_right\">17.8%</td>\n<td class=\"gt_row gt_right\">28.4%</td>\n<td class=\"gt_row gt_right\">38.7%</td>\n<td class=\"gt_row gt_right\">15.0%</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 2 - Middle</td>\n<td class=\"gt_row gt_right\">971</td>\n<td class=\"gt_row gt_right\">3,543,062</td>\n<td class=\"gt_row gt_right\">23.7%</td>\n<td class=\"gt_row gt_right\">21.8%</td>\n<td class=\"gt_row gt_right\">39.0%</td>\n<td class=\"gt_row gt_right\">15.5%</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 3 - Shrinking</td>\n<td class=\"gt_row gt_right\">453</td>\n<td class=\"gt_row gt_right\">2,009,535</td>\n<td class=\"gt_row gt_right\">28.9%</td>\n<td class=\"gt_row gt_right\">23.2%</td>\n<td class=\"gt_row gt_right\">35.8%</td>\n<td class=\"gt_row gt_right\">12.1%</td></tr>\n    <tr><td class=\"gt_row gt_left\">Uncategorized</td>\n<td class=\"gt_row gt_right\">65</td>\n<td class=\"gt_row gt_right\">42,565</td>\n<td class=\"gt_row gt_right\">18.8%</td>\n<td class=\"gt_row gt_right\">33.2%</td>\n<td class=\"gt_row gt_right\">34.1%</td>\n<td class=\"gt_row gt_right\">14.0%</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n### Disability\nNext up, we'll examine disability, primarily be calculating the average share of each city that is disabled.\n\n![](08_neighborhood_change/images/07_Disability.png)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income |> \n  group_by(change_cat_70.19) |> \n  summarise(\nTracts = n(), \nP_Disabled = mean(P_Disabled, na.rm=TRUE)\n) |> \n  gt() |> \n  fmt_percent(3, decimals = 1)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ucwiddhsrs\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#ucwiddhsrs .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ucwiddhsrs .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ucwiddhsrs .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ucwiddhsrs .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ucwiddhsrs .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ucwiddhsrs .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ucwiddhsrs .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ucwiddhsrs .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ucwiddhsrs .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ucwiddhsrs .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ucwiddhsrs .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ucwiddhsrs .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ucwiddhsrs .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ucwiddhsrs .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ucwiddhsrs .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ucwiddhsrs .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ucwiddhsrs .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ucwiddhsrs .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ucwiddhsrs .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ucwiddhsrs .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ucwiddhsrs .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ucwiddhsrs .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ucwiddhsrs .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ucwiddhsrs .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ucwiddhsrs .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ucwiddhsrs .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ucwiddhsrs .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ucwiddhsrs .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ucwiddhsrs .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ucwiddhsrs .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ucwiddhsrs .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ucwiddhsrs .gt_left {\n  text-align: left;\n}\n\n#ucwiddhsrs .gt_center {\n  text-align: center;\n}\n\n#ucwiddhsrs .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ucwiddhsrs .gt_font_normal {\n  font-weight: normal;\n}\n\n#ucwiddhsrs .gt_font_bold {\n  font-weight: bold;\n}\n\n#ucwiddhsrs .gt_font_italic {\n  font-style: italic;\n}\n\n#ucwiddhsrs .gt_super {\n  font-size: 65%;\n}\n\n#ucwiddhsrs .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#ucwiddhsrs .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ucwiddhsrs .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ucwiddhsrs .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ucwiddhsrs .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ucwiddhsrs .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ucwiddhsrs .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">change_cat_70.19</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Tracts</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Disabled</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">City 1 - Growing</td>\n<td class=\"gt_row gt_right\">678</td>\n<td class=\"gt_row gt_right\">9.7%</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 2 - Middle</td>\n<td class=\"gt_row gt_right\">971</td>\n<td class=\"gt_row gt_right\">10.8%</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 3 - Shrinking</td>\n<td class=\"gt_row gt_right\">453</td>\n<td class=\"gt_row gt_right\">12.0%</td></tr>\n    <tr><td class=\"gt_row gt_left\">Uncategorized</td>\n<td class=\"gt_row gt_right\">65</td>\n<td class=\"gt_row gt_right\">17.4%</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n### Housing\nNext up, we'll look at housing tenure (the balance between owners and renters), as well as cost burden (the share of households paying more than 30 percent of their income towards housing costs.\n\n![](08_neighborhood_change/images/08_Housing.png)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income |> \n  group_by(change_cat_70.19) |> \n  summarise(\nTracts = n(), \nP_Own = mean(P_Own, na.rm=TRUE),\nP_Rent = mean(P_Rent, na.rm=TRUE),\nP_CostBurden = mean(P_CostBurden, na.rm=TRUE)\n) |> \n  gt() |> \n  fmt_percent(3:5, decimals = 1)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"mwwyazomrv\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#mwwyazomrv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mwwyazomrv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mwwyazomrv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mwwyazomrv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mwwyazomrv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mwwyazomrv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mwwyazomrv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mwwyazomrv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mwwyazomrv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mwwyazomrv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mwwyazomrv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mwwyazomrv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mwwyazomrv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mwwyazomrv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mwwyazomrv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mwwyazomrv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mwwyazomrv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mwwyazomrv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mwwyazomrv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mwwyazomrv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mwwyazomrv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mwwyazomrv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mwwyazomrv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mwwyazomrv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mwwyazomrv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mwwyazomrv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mwwyazomrv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mwwyazomrv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mwwyazomrv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mwwyazomrv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mwwyazomrv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mwwyazomrv .gt_left {\n  text-align: left;\n}\n\n#mwwyazomrv .gt_center {\n  text-align: center;\n}\n\n#mwwyazomrv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mwwyazomrv .gt_font_normal {\n  font-weight: normal;\n}\n\n#mwwyazomrv .gt_font_bold {\n  font-weight: bold;\n}\n\n#mwwyazomrv .gt_font_italic {\n  font-style: italic;\n}\n\n#mwwyazomrv .gt_super {\n  font-size: 65%;\n}\n\n#mwwyazomrv .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#mwwyazomrv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mwwyazomrv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mwwyazomrv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mwwyazomrv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mwwyazomrv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mwwyazomrv .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">change_cat_70.19</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Tracts</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Own</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Rent</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_CostBurden</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">City 1 - Growing</td>\n<td class=\"gt_row gt_right\">678</td>\n<td class=\"gt_row gt_right\">36.1%</td>\n<td class=\"gt_row gt_right\">63.9%</td>\n<td class=\"gt_row gt_right\">39.2%</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 2 - Middle</td>\n<td class=\"gt_row gt_right\">971</td>\n<td class=\"gt_row gt_right\">45.4%</td>\n<td class=\"gt_row gt_right\">54.6%</td>\n<td class=\"gt_row gt_right\">46.6%</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 3 - Shrinking</td>\n<td class=\"gt_row gt_right\">453</td>\n<td class=\"gt_row gt_right\">22.7%</td>\n<td class=\"gt_row gt_right\">77.3%</td>\n<td class=\"gt_row gt_right\">55.6%</td></tr>\n    <tr><td class=\"gt_row gt_left\">Uncategorized</td>\n<td class=\"gt_row gt_right\">65</td>\n<td class=\"gt_row gt_right\">37.5%</td>\n<td class=\"gt_row gt_right\">62.5%</td>\n<td class=\"gt_row gt_right\">51.2%</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n### Employment\n\nLet's finally calculate labor force participation and unemployment by city.\n\n![](08_neighborhood_change/images/09_Labor.png)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income |> \n  group_by(change_cat_70.19) |> \n  summarise(\nTracts = n(), \nP_Unemp = mean(P_Unemp, na.rm=TRUE),\nP_LabForce = mean(P_LabForce, na.rm=TRUE)\n) |> \n  gt() |> \n  fmt_percent(3:4, decimals = 1)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"yqfacwqlas\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#yqfacwqlas .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yqfacwqlas .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yqfacwqlas .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yqfacwqlas .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yqfacwqlas .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqfacwqlas .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yqfacwqlas .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yqfacwqlas .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yqfacwqlas .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yqfacwqlas .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yqfacwqlas .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yqfacwqlas .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yqfacwqlas .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yqfacwqlas .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yqfacwqlas .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yqfacwqlas .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yqfacwqlas .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfacwqlas .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yqfacwqlas .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yqfacwqlas .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfacwqlas .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yqfacwqlas .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yqfacwqlas .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqfacwqlas .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfacwqlas .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yqfacwqlas .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yqfacwqlas .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqfacwqlas .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yqfacwqlas .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfacwqlas .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yqfacwqlas .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfacwqlas .gt_left {\n  text-align: left;\n}\n\n#yqfacwqlas .gt_center {\n  text-align: center;\n}\n\n#yqfacwqlas .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yqfacwqlas .gt_font_normal {\n  font-weight: normal;\n}\n\n#yqfacwqlas .gt_font_bold {\n  font-weight: bold;\n}\n\n#yqfacwqlas .gt_font_italic {\n  font-style: italic;\n}\n\n#yqfacwqlas .gt_super {\n  font-size: 65%;\n}\n\n#yqfacwqlas .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#yqfacwqlas .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yqfacwqlas .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yqfacwqlas .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yqfacwqlas .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yqfacwqlas .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yqfacwqlas .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">change_cat_70.19</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Tracts</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Unemp</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_LabForce</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">City 1 - Growing</td>\n<td class=\"gt_row gt_right\">678</td>\n<td class=\"gt_row gt_right\">5.0%</td>\n<td class=\"gt_row gt_right\">68.2%</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 2 - Middle</td>\n<td class=\"gt_row gt_right\">971</td>\n<td class=\"gt_row gt_right\">6.5%</td>\n<td class=\"gt_row gt_right\">61.8%</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 3 - Shrinking</td>\n<td class=\"gt_row gt_right\">453</td>\n<td class=\"gt_row gt_right\">8.5%</td>\n<td class=\"gt_row gt_right\">59.0%</td></tr>\n    <tr><td class=\"gt_row gt_left\">Uncategorized</td>\n<td class=\"gt_row gt_right\">65</td>\n<td class=\"gt_row gt_right\">13.0%</td>\n<td class=\"gt_row gt_right\">58.6%</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nAlso calculate average employment by industry for the three cities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnyc_income |> \n  group_by(change_cat_70.19) |> \n  summarise(\nTracts = n(), \nP_Emp_Ag = mean(P_Emp_Ag, na.rm=TRUE),\nP_Emp_Const = mean(P_Emp_Const, na.rm=TRUE),\nP_Emp_Manuf = mean(P_Emp_Manuf, na.rm=TRUE),\nP_Emp_Wholesale = mean(P_Emp_Wholesale, na.rm=TRUE),\nP_Emp_Retail = mean(P_Emp_Retail, na.rm=TRUE),\nP_Emp_Transportation = mean(P_Emp_Transportation, na.rm=TRUE),\nP_Emp_FIRE = mean(P_Emp_FIRE, na.rm=TRUE),\nP_Emp_Management = mean(P_Emp_Management, na.rm=TRUE),\nP_Emp_Education = mean(P_Emp_Education, na.rm=TRUE),\nP_Emp_Arts = mean(P_Emp_Arts, na.rm=TRUE),\nP_Emp_Other = mean(P_Emp_Other, na.rm=TRUE),\nP_Emp_PA = mean(P_Emp_PA, na.rm=TRUE)\n) |> \n  gt() |> \n  fmt_percent(3:14, decimals = 1)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ikeqwndsdq\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#ikeqwndsdq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ikeqwndsdq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ikeqwndsdq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ikeqwndsdq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ikeqwndsdq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ikeqwndsdq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ikeqwndsdq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ikeqwndsdq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ikeqwndsdq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ikeqwndsdq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ikeqwndsdq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ikeqwndsdq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ikeqwndsdq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ikeqwndsdq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ikeqwndsdq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ikeqwndsdq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ikeqwndsdq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ikeqwndsdq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ikeqwndsdq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ikeqwndsdq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ikeqwndsdq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ikeqwndsdq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ikeqwndsdq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ikeqwndsdq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ikeqwndsdq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ikeqwndsdq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ikeqwndsdq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ikeqwndsdq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ikeqwndsdq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ikeqwndsdq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ikeqwndsdq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ikeqwndsdq .gt_left {\n  text-align: left;\n}\n\n#ikeqwndsdq .gt_center {\n  text-align: center;\n}\n\n#ikeqwndsdq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ikeqwndsdq .gt_font_normal {\n  font-weight: normal;\n}\n\n#ikeqwndsdq .gt_font_bold {\n  font-weight: bold;\n}\n\n#ikeqwndsdq .gt_font_italic {\n  font-style: italic;\n}\n\n#ikeqwndsdq .gt_super {\n  font-size: 65%;\n}\n\n#ikeqwndsdq .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#ikeqwndsdq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ikeqwndsdq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ikeqwndsdq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ikeqwndsdq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ikeqwndsdq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ikeqwndsdq .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">change_cat_70.19</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Tracts</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Emp_Ag</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Emp_Const</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Emp_Manuf</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Emp_Wholesale</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Emp_Retail</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Emp_Transportation</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Emp_FIRE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Emp_Management</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Emp_Education</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Emp_Arts</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Emp_Other</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">P_Emp_PA</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">City 1 - Growing</td>\n<td class=\"gt_row gt_right\">678</td>\n<td class=\"gt_row gt_right\">0.1%</td>\n<td class=\"gt_row gt_right\">3.8%</td>\n<td class=\"gt_row gt_right\">3.0%</td>\n<td class=\"gt_row gt_right\">2.0%</td>\n<td class=\"gt_row gt_right\">7.8%</td>\n<td class=\"gt_row gt_right\">4.6%</td>\n<td class=\"gt_row gt_right\">11.8%</td>\n<td class=\"gt_row gt_right\">18.0%</td>\n<td class=\"gt_row gt_right\">24.4%</td>\n<td class=\"gt_row gt_right\">9.9%</td>\n<td class=\"gt_row gt_right\">4.5%</td>\n<td class=\"gt_row gt_right\">4.1%</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 2 - Middle</td>\n<td class=\"gt_row gt_right\">971</td>\n<td class=\"gt_row gt_right\">0.1%</td>\n<td class=\"gt_row gt_right\">6.3%</td>\n<td class=\"gt_row gt_right\">3.2%</td>\n<td class=\"gt_row gt_right\">2.3%</td>\n<td class=\"gt_row gt_right\">9.6%</td>\n<td class=\"gt_row gt_right\">8.5%</td>\n<td class=\"gt_row gt_right\">7.4%</td>\n<td class=\"gt_row gt_right\">10.5%</td>\n<td class=\"gt_row gt_right\">30.2%</td>\n<td class=\"gt_row gt_right\">9.6%</td>\n<td class=\"gt_row gt_right\">5.4%</td>\n<td class=\"gt_row gt_right\">4.5%</td></tr>\n    <tr><td class=\"gt_row gt_left\">City 3 - Shrinking</td>\n<td class=\"gt_row gt_right\">453</td>\n<td class=\"gt_row gt_right\">0.2%</td>\n<td class=\"gt_row gt_right\">6.4%</td>\n<td class=\"gt_row gt_right\">3.6%</td>\n<td class=\"gt_row gt_right\">2.2%</td>\n<td class=\"gt_row gt_right\">11.2%</td>\n<td class=\"gt_row gt_right\">8.4%</td>\n<td class=\"gt_row gt_right\">6.2%</td>\n<td class=\"gt_row gt_right\">9.2%</td>\n<td class=\"gt_row gt_right\">28.5%</td>\n<td class=\"gt_row gt_right\">13.0%</td>\n<td class=\"gt_row gt_right\">6.6%</td>\n<td class=\"gt_row gt_right\">3.0%</td></tr>\n    <tr><td class=\"gt_row gt_left\">Uncategorized</td>\n<td class=\"gt_row gt_right\">65</td>\n<td class=\"gt_row gt_right\">0.0%</td>\n<td class=\"gt_row gt_right\">2.4%</td>\n<td class=\"gt_row gt_right\">6.3%</td>\n<td class=\"gt_row gt_right\">0.8%</td>\n<td class=\"gt_row gt_right\">7.1%</td>\n<td class=\"gt_row gt_right\">3.1%</td>\n<td class=\"gt_row gt_right\">11.7%</td>\n<td class=\"gt_row gt_right\">19.7%</td>\n<td class=\"gt_row gt_right\">26.5%</td>\n<td class=\"gt_row gt_right\">7.5%</td>\n<td class=\"gt_row gt_right\">7.6%</td>\n<td class=\"gt_row gt_right\">4.1%</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n## Describing our Three Cities\n\n\n# Lab Summary\n\nIn this lab, you started working with harmonized census data in order to describe trajectories of neighborhood change. You spent lots of time cleaning your data and preparing it for further analysis. You joined to the historical census data current ACS data, and then compared the current demographic attributes of those places based upon their historical trajectories of income change.\n\nIn this lab, you've had the opportunitiy to work (more) independently, relying upon your past skills and R skillset. The focus in this lab has been on data cleaning and manipulation. \n\nYour next steps might be to spend more time visualizing and analyzing the resulting data. Based upon what we've done here, here are some thoughts on some ways to extend this lab.\n\n-   Join the \"long\" income data to census geographies and visualize the time series.\n-   Map out census tracts based upon their belonging to the three cities, both the entire region, and for each county.\n-   Use the five income labels to describe trajectories of change for each census tract. Consider categorizing census tracts based upon their long run trajectories.\n-   Examine the demographics of census tracts in each decade (we could have pulled that from the LTDB sample data). How have demographic attributes changed of places in each income category?\n\n## Lab Evaluation\n\nIn evaluating your lab submission, we'll be paying attention to the following:\n\n-   Proper import, cleaning, and formatting of LTDB data, paying particular attention to building reproducible data pipelines that you could use for any geographic location.\n\n-   Thoughtful reflection on data process and outputs.\n\nAs you get into the lab, please feel welcome to ask us questions, and please share where you're struggling with us and with others in the class.\n\n## References\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}